package com.mediafactory;

import com.mediafactory.prompt.*;
import com.mediafactory.prompt.PromptModels.*;
import com.mediafactory.provider.*;
import com.mediafactory.provider.ProviderTypes.*;
import com.mediafactory.provider.routing.*;
import com.mediafactory.provider.resilience.*;
import com.mediafactory.service.*;
import com.mediafactory.storage.MediaStorage;
import com.mediafactory.quality.TechnicalQa;
import org.junit.jupiter.api.*;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.test.context.*;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.*;
import org.testcontainers.utility.DockerImageName;
import java.util.*;
import java.net.*;
import java.net.http.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;
import static org.assertj.core.api.Assertions.*;

@Tag("integration") @Testcontainers
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"media.worker.enabled=false"})
class PromptIntegrationTest {
 @Container static PostgreSQLContainer<?> postgres=new PostgreSQLContainer<>(DockerImageName.parse("pgvector/pgvector:pg17").asCompatibleSubstituteFor("postgres"));
 @DynamicPropertySource static void config(DynamicPropertyRegistry r){r.add("spring.datasource.url",postgres::getJdbcUrl);r.add("spring.datasource.username",postgres::getUsername);r.add("spring.datasource.password",postgres::getPassword);r.add("media.storage.root",()->"build/prompt-test-media");}
 @Autowired PromptCatalog catalog;@Autowired PromptEngine engine;@Autowired FactoryService service;@Autowired JdbcClient db;@Autowired TransactionTemplate tx;
 @Autowired ImageGenerationProperties properties;@Autowired ProviderRateLimiter limiter;@Autowired RetryDecisionService retry;@Autowired GenerationAttemptRepository attempts;@Autowired ProviderObservability telemetry;@Autowired MediaStorage storage;@Autowired TechnicalQa qa;
 @org.springframework.beans.factory.annotation.Value("${local.server.port}") int port;
 UUID template,version,concept,collection;
 List<PromptVariableDefinition> definitions(){return List.of(new PromptVariableDefinition("subject","Subject","",VariableType.STRING,true,null,List.of(),null,null,1,100,0),new PromptVariableDefinition("lighting","Lighting","",VariableType.ENUM,true,"NEON",List.of("NEON","SOFT"),null,null,null,null,1));}
 VersionInput input(String positive,Integer revision){return new VersionInput(positive,"Avoid blurry {{subject}}",definitions(),"Test change",revision,null);}
 @BeforeEach void setup(){db.sql("truncate projects,prompt_templates,prompt_presets,prompt_experiments,provider_runtime,provider_request_events cascade").update();template=(UUID)catalog.createTemplate(new TemplateInput("animals","Animals","","WALLPAPER",null,null)).get("id");version=(UUID)catalog.createVersion(template,input("A {{subject}} in {{lighting}} light",null)).get("id");var p=service.project("Prompt tests","");collection=(UUID)service.collection((UUID)p.get("id"),"Collection").get("id");concept=(UUID)service.concept(collection,"Concept","Legacy text").get("id");}
 PromptRenderRequest request(UUID v,List<String> presets,String suffix){return new PromptRenderRequest(v,Map.of("subject","wolf"),presets,"mock",null,null,null,"wallpaper",suffix,null,null,null);}
 Map<String,Object> generate(UUID v,String key){return service.generatePrompt(concept,128,128,key,null,ImageOptions.defaults(),request(v,List.of(),null));}
 GenerationWorker worker(ImageGenerationProvider provider){return new GenerationWorker(db,tx,service,new ImageProviderRouter(List.of(provider),properties),properties,limiter,retry,attempts,telemetry,storage,qa);}
 @Test void draftEditPublishPreviewAndPublishedProtection(){catalog.editVersion(version,input("Premium {{subject}}, {{lighting}}",0));assertThatThrownBy(()->catalog.editVersion(version,input("stale",0))).hasMessageContaining("Revision conflict");catalog.publish(version,1);assertThatThrownBy(()->catalog.editVersion(version,input("changed",2))).hasMessageContaining("immutable");var preview=engine.preview(request(version,List.of(),null));assertThat(preview.toString()).contains("Premium wolf, NEON","Avoid blurry wolf","Negative constraints");assertThat(service.list("generations")).isEmpty();assertThat(service.list("generation_costs")).isEmpty();}
 @Test void invalidSyntaxAndUndefinedVariablesCannotPublish(){catalog.editVersion(version,input("{{missing}}",0));assertThatThrownBy(()->catalog.publish(version,1)).hasMessageContaining("Undefined");catalog.editVersion(version,input("{{#script}}",1));assertThatThrownBy(()->catalog.publish(version,2)).hasMessageContaining("syntax");assertThat(catalog.version(version).get("status")).isEqualTo("DRAFT");}
 @Test void databaseGuardsPublishedContentAndSnapshotAttribution(){catalog.publish(version,0);assertThatThrownBy(()->db.sql("update prompt_versions set positive_template='changed' where id=?").param(version).update()).hasMessageContaining("immutable");assertThatThrownBy(()->db.sql("delete from prompt_variable_definitions where prompt_version_id=?").param(version).update()).hasMessageContaining("immutable");var g=generate(version,"immutable");assertThatThrownBy(()->db.sql("update rendered_prompt_snapshots set adapted_positive_prompt='changed' where generation_id=?").param(g.get("id")).update()).hasMessageContaining("Immutable");assertThatThrownBy(()->db.sql("update generations set prompt='changed' where id=?").param(g.get("id")).update()).hasMessageContaining("immutable");}
 @Test void generationStoresExactProviderPromptAndVersionTwoCannotChangeIt(){catalog.publish(version,0);var g=generate(version,"v1");var observed=new AtomicReference<Request>();try(var worker=worker(new MockProviders(){@Override public Result<Media> generate(Request r){observed.set(r);return super.generate(r);}})){worker.execute(worker.claim());}
  var snapshot=engine.snapshots((UUID)g.get("id")).getFirst();assertThat(observed.get().prompt()).isEqualTo(snapshot.get("adapted_positive_prompt"));assertThat(snapshot.get("canonical_negative_prompt")).isEqualTo("Avoid blurry wolf\n\nUI, text");assertThat(service.one("generations",(UUID)g.get("id")).get("status")).isEqualTo("QA_PENDING");
  UUID v2=(UUID)catalog.createVersion(template,new VersionInput(null,null,null,"Copy",null,version)).get("id");catalog.editVersion(v2,input("Different {{subject}} {{lighting}}",0));catalog.publish(v2,1);assertThat(engine.snapshots((UUID)g.get("id")).getFirst()).isEqualTo(snapshot);assertThat(catalog.version(version).get("positive_template")).isEqualTo("A {{subject}} in {{lighting}} light");
  var regenerated=service.regenerate((UUID)service.list("assets").getFirst().get("id"),"regen");assertThat(engine.snapshots((UUID)regenerated.get("id")).getFirst().get("adapted_positive_prompt")).isEqualTo(snapshot.get("adapted_positive_prompt"));
 }
 @Test void presetRevisionAndDefaultChangesDoNotAffectRetry(){catalog.publish(version,0);var preset=catalog.createPreset(new PresetInput("AMOLED","AMOLED","","STYLE",null,"Deep blacks","gray background",null));var g=service.generatePrompt(concept,128,128,"retry",null,ImageOptions.defaults(),request(version,List.of("AMOLED"),"gold rim"));String before=engine.snapshots((UUID)g.get("id")).toString();var seen=new ArrayList<String>();var provider=new MockProviders(){@Override public Result<Media> generate(Request r){seen.add(r.prompt());if(seen.size()==1)throw new ImageGenerationException(ImageGenerationException.Type.UNAVAILABLE,"Temporary fixture failure");return super.generate(r);}};
  try(var w=worker(provider)){w.execute(w.claim());catalog.updatePreset((UUID)preset.get("id"),new PresetInput(null,null,null,null,null,"Changed blacks","different",0));db.sql("update jobs set available_at=now() where generation_id=?").param(g.get("id")).update();w.execute(w.claim());}
  assertThat(seen).hasSize(2);assertThat(seen.get(0)).isEqualTo(seen.get(1)).contains("Deep blacks").doesNotContain("Changed blacks");assertThat(engine.snapshots((UUID)g.get("id")).toString()).isEqualTo(before);assertThat(db.sql("select count(distinct prompt_snapshot_id) from generation_attempts").query(Integer.class).single()).isEqualTo(1);
 }
 UUID experiment(String scope,boolean overrides){catalog.publish(version,0);UUID v2=(UUID)catalog.createVersion(template,new VersionInput(null,null,null,"Variant",null,version)).get("id");catalog.publish(v2,0);var e=catalog.createExperiment(new ExperimentInput("Lighting test","",scope,scope.equals("PROMPT_TEMPLATE")?template:null,scope.equals("COLLECTION")?collection:null,scope.equals("PIPELINE")?"wallpaper":null,overrides,List.of(new VariantInput("A","A",version,5000),new VariantInput("B","B",v2,5000))));UUID id=(UUID)e.get("id");catalog.changeExperiment(id,"RUNNING",0);return id;}
 @Test void experimentAssignsDeterministicallyAndReplaySurvivesPause(){UUID exp=experiment("PROMPT_TEMPLATE",false);var first=generate(version,"stable");var variant=ExperimentAssignment.assign(exp,"stable",catalog.variants(exp));assertThat(first.get("experiment_variant_id")).isEqualTo(variant.get("id"));assertThat(first.get("prompt_version_id")).isEqualTo(variant.get("prompt_version_id"));catalog.changeExperiment(exp,"PAUSED",1);assertThat(generate(version,"stable").get("id")).isEqualTo(first.get("id"));assertThat(generate(version,"new-after-pause").get("experiment_id")).isNull();assertThat(engine.snapshots((UUID)first.get("id")).getFirst().get("experiment_id")).isEqualTo(exp);}
 @Test void experimentScopesAndOverridesAreEnforced(){UUID exp=experiment("COLLECTION",false);assertThatThrownBy(()->service.generatePrompt(concept,128,128,"override",null,ImageOptions.defaults(),request(version,List.of(),"gold"))).hasMessageContaining("overrides");var other=service.collection((UUID)service.list("projects").getFirst().get("id"),"Other");UUID otherConcept=(UUID)service.concept((UUID)other.get("id"),"Other","x").get("id");var g=service.generatePrompt(otherConcept,128,128,"outside",null,ImageOptions.defaults(),request(version,List.of(),null));assertThat(g.get("experiment_id")).isNull();var r=new PromptRenderRequest(version,Map.of("subject","wolf"),List.of(),"mock",exp,"preview",otherConcept,null,null,null,null,null);assertThatThrownBy(()->engine.preview(r)).hasMessageContaining("scope");}
 @Test void pipelineExperimentAndAllowedOverridesAreAttributed(){UUID exp=experiment("PIPELINE",true);var g=service.generatePrompt(concept,128,128,"pipeline",null,ImageOptions.defaults(),request(version,List.of(),"gold"));assertThat(g.get("experiment_id")).isEqualTo(exp);assertThat(engine.snapshots((UUID)g.get("id")).getFirst().get("canonical_positive_prompt").toString()).endsWith("gold");}
 @Test void experimentConfigurationStaysImmutableAfterPauseAndCompletion(){UUID exp=experiment("PROMPT_TEMPLATE",false);assertThatThrownBy(()->db.sql("update prompt_experiment_variants set weight=6000 where experiment_id=?").param(exp).update()).hasMessageContaining("immutable");catalog.changeExperiment(exp,"PAUSED",1);assertThatThrownBy(()->db.sql("update prompt_experiments set allow_overrides=true where id=?").param(exp).update()).hasMessageContaining("immutable");catalog.changeExperiment(exp,"RUNNING",2);catalog.changeExperiment(exp,"COMPLETED",3);assertThatThrownBy(()->catalog.changeExperiment(exp,"RUNNING",4)).hasMessageContaining("Illegal");}
 @Test void concurrentVersionCopiesGetUniqueNumbers() throws Exception {catalog.publish(version,0);try(var pool=Executors.newFixedThreadPool(2)){var tasks=new ArrayList<Future<Map<String,Object>>>();for(int i=0;i<2;i++)tasks.add(pool.submit(()->catalog.createVersion(template,new VersionInput(null,null,null,"Copy",null,version))));var a=tasks.get(0).get(10,TimeUnit.SECONDS);var b=tasks.get(1).get(10,TimeUnit.SECONDS);assertThat(a.get("version")).isNotEqualTo(b.get("version"));}}
 @Test void rawRequestsHaveExplicitAdHocSnapshots(){var g=service.generate(concept,"Raw prompt {{literal}}",128,128,"raw",null);var s=engine.snapshots((UUID)g.get("id")).getFirst();assertThat(s).containsEntry("kind","AD_HOC").containsEntry("template_id",null).containsEntry("adapted_positive_prompt","Raw prompt {{literal}}");}
 @Test void httpGenerationAndPreviewReturnStructuredVariableErrors() throws Exception {catalog.publish(version,0);var client=HttpClient.newHttpClient();String body=PromptCatalog.JSON.writeValueAsString(Map.of("conceptId",concept,"promptVersionId",version,"variables",Map.of("subject","wolf"),"provider","mock"));var request=HttpRequest.newBuilder(URI.create("http://localhost:"+port+"/api/v1/generations/images")).header("Content-Type","application/json").header("Idempotency-Key","http-template").POST(HttpRequest.BodyPublishers.ofString(body)).build();assertThat(client.send(request,HttpResponse.BodyHandlers.ofString()).statusCode()).isEqualTo(202);
  var bad=HttpRequest.newBuilder(URI.create("http://localhost:"+port+"/api/v1/prompts/render")).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(PromptCatalog.JSON.writeValueAsString(Map.of("promptVersionId",version,"variables",Map.of("subject","wolf","lighting","LASER"))))).build();var error=client.send(bad,HttpResponse.BodyHandlers.ofString());assertThat(error.statusCode()).isEqualTo(400);assertThat(error.body()).contains("PROMPT_VARIABLE_INVALID","lighting");
 }
}
