package com.mediafactory;
import com.mediafactory.prompt.*;
import com.mediafactory.prompt.PromptModels.*;
import com.mediafactory.provider.MockProviders;
import org.junit.jupiter.api.Test;
import java.util.*;
import java.math.BigDecimal;
import static org.assertj.core.api.Assertions.*;

class PromptEngineTest {
 final SafePromptTemplateRenderer renderer=new SafePromptTemplateRenderer();final PromptVariableValidator validator=new PromptVariableValidator();
 PromptVariableDefinition definition(String name,VariableType type,boolean required,Object fallback,List<String> allowed){return new PromptVariableDefinition(name,name,"",type,required,fallback,allowed,null,null,null,null,0);}
 @Test void renderingIsSinglePassAndPreservesLiteralWhitespace(){assertThat(renderer.render("A {{subject}}\r\n\n  B",Map.of("subject","{{notEvaluated}} $1 \\" )).text()).isEqualTo("A {{notEvaluated}} $1 \\\n\n  B");}
 @Test void missingVariableIdentifiesName(){assertThatThrownBy(()->renderer.render("{{subject}}",Map.of())).isInstanceOfSatisfying(PromptException.class,e->assertThat(e.variable()).isEqualTo("subject"));}
 @Test void rejectsExecutableAndMalformedSyntax(){for(String input:List.of("{{#each x}}","{{user.name}}","{{x","{{{x}}}"))assertThatThrownBy(()->renderer.references(input)).isInstanceOf(PromptException.class);}
 @Test void defaultsAndOptionalVariablesResolveDeterministically(){var defs=List.of(definition("subject",VariableType.STRING,true,"wolf",null),definition("background",VariableType.STRING,false,null,null));assertThat(validator.resolve(defs,Map.of())).containsEntry("subject","wolf").containsEntry("background","");}
 @Test void requiredAndUnknownVariablesFail(){var defs=List.of(definition("subject",VariableType.STRING,true,null,null));assertThatThrownBy(()->validator.resolve(defs,Map.of())).hasMessageContaining("Required");assertThatThrownBy(()->validator.resolve(defs,Map.of("wrong","x"))).hasMessageContaining("Unknown variable");}
 @Test void enumAndDefaultValidation(){var d=definition("light",VariableType.ENUM,true,"NEON",List.of("NEON","SOFT"));assertThat(validator.resolve(List.of(d),Map.of())).containsEntry("light","NEON");assertThatThrownBy(()->validator.resolve(List.of(d),Map.of("light","LASER"))).hasMessageContaining("enum");assertThatThrownBy(()->validator.definitions(List.of(definition("light",VariableType.ENUM,false,"INVALID",List.of("NEON"))))) .isInstanceOf(PromptException.class);}
 @Test void numericTypesAndBoundsAreStrict(){var d=new PromptVariableDefinition("count","Count","",VariableType.INTEGER,true,null,List.of(),BigDecimal.ONE,BigDecimal.TEN,null,null,0);assertThatThrownBy(()->validator.resolve(List.of(d),Map.of("count",1.5))).hasMessageContaining("integer");assertThatThrownBy(()->validator.resolve(List.of(d),Map.of("count",11))).hasMessageContaining("maximum");assertThatThrownBy(()->validator.resolve(List.of(d),Map.of("count","2"))).hasMessageContaining("number");assertThat(validator.resolve(List.of(d),Map.of("count",2)).get("count")).isEqualTo(new BigDecimal("2"));}
 @Test void booleanListsAndLengthAreValidated(){var bool=definition("flag",VariableType.BOOLEAN,true,null,null);assertThatThrownBy(()->validator.resolve(List.of(bool),Map.of("flag","true"))).hasMessageContaining("boolean");var list=definition("colors",VariableType.STRING_LIST,true,null,null);assertThat(renderer.render("{{colors}}",validator.resolve(List.of(list),Map.of("colors",List.of("red","blue")))).text()).isEqualTo("red, blue");assertThatThrownBy(()->validator.resolve(List.of(list),Map.of("colors",List.of(1)))).hasMessageContaining("strings");}
 @Test void duplicateDefinitionsAndLengthBoundsFail(){var d=new PromptVariableDefinition("s","s","",VariableType.STRING,true,null,List.of(),null,null,2,4,0);assertThatThrownBy(()->validator.definitions(List.of(d,d))).hasMessageContaining("duplicate");assertThatThrownBy(()->validator.resolve(List.of(d),Map.of("s","12345"))).hasMessageContaining("Length");}
 @Test void positiveAndNegativeCompositionHaveStableOrder(){var c=new PromptComposer();assertThat(c.compose(" base ",List.of("first","second"),"pipeline","manual")).isEqualTo("base\n\nfirst\n\nsecond\n\npipeline\n\nmanual");assertThat(c.constraints("stock").get("negative")).contains("trademarks");assertThat(c.lint("no text, include text, include text","")).hasSize(3);}
 @Test void providerAdaptersNeverDiscardNegativeAndDifferTransparently(){var p=new CanonicalPrompt("wolf","watermark",Map.of(),List.of());var caps=new MockProviders().capabilities();var openai=new PromptAdapters.ConstraintAdapter("openai","Avoid:\n").adapt(p,caps);var mock=new PromptAdapters.ConstraintAdapter("mock","Negative:\n").adapt(p,caps);assertThat(openai.positivePrompt()).isEqualTo("wolf\n\nAvoid:\nwatermark");assertThat(mock.positivePrompt()).isNotEqualTo(openai.positivePrompt());assertThat(openai.warnings()).isNotEmpty();assertThat(openai.negativePrompt()).isEmpty();}
 @Test void promptLengthIsRejectedNotTruncated(){assertThatThrownBy(()->new PromptAdapters.ConstraintAdapter("mock","Avoid ").adapt(new CanonicalPrompt("x".repeat(10001),"",Map.of(),List.of()),new MockProviders().capabilities())).hasMessageContaining("no truncation");}
 @Test void nativeNegativeCapabilityKeepsBothChannels(){var c=new MockProviders().capabilities();var nativeCaps=new com.mediafactory.provider.ProviderCapabilities(c.supportedAspectRatios(),c.supportedFormats(),c.supportedQualities(),c.supportedSizes(),c.arbitraryDimensions(),true,c.supportsSeed(),c.supportsReferenceImage(),c.supportsTransparentBackground(),c.maximumImages());var adapted=new PromptAdapters.ConstraintAdapter("future","Avoid ").adapt(new CanonicalPrompt("wolf","blurry",Map.of(),List.of()),nativeCaps);assertThat(adapted.positivePrompt()).isEqualTo("wolf");assertThat(adapted.negativePrompt()).isEqualTo("blurry");assertThat(adapted.strategy()).isEqualTo("NEGATIVE_PROMPT_SEPARATE_FIELD_V1");}
 @Test void decimalAndBooleanDefaultsRemainTyped(){var defs=List.of(definition("ratio",VariableType.DECIMAL,true,new BigDecimal("1.250"),null),definition("enabled",VariableType.BOOLEAN,true,true,null));var values=validator.resolve(defs,Map.of());assertThat(values.get("enabled")).isEqualTo(true);assertThat(renderer.render("{{ratio}} {{enabled}}",values).text()).isEqualTo("1.25 true");}
 @Test void equalAndThreeWayWeightsAllocateWithoutRandomness(){UUID experiment=UUID.fromString("00000000-0000-0000-0000-000000000099");for(var weights:List.of(List.of(5000,5000),List.of(4000,3000,3000))){var variants=new ArrayList<Map<String,Object>>();for(int i=0;i<weights.size();i++)variants.add(Map.of("key",String.valueOf(i),"weight",weights.get(i)));var counts=new int[weights.size()];for(int i=0;i<10000;i++)counts[Integer.parseInt((String)ExperimentAssignment.assign(experiment,"sample-"+i,variants).get("key"))]++;for(int i=0;i<weights.size();i++)assertThat(counts[i]).isBetween(weights.get(i)-200,weights.get(i)+200);}}
 @Test void deterministicWeightedAssignmentsHaveStableDistribution(){var id=UUID.fromString("00000000-0000-0000-0000-000000000001");var variants=List.<Map<String,Object>>of(Map.of("key","A","weight",8000),Map.of("key","B","weight",2000));int a=0;for(int i=0;i<10000;i++){String key="generation-"+i;var chosen=ExperimentAssignment.assign(id,key,variants);assertThat(ExperimentAssignment.assign(id,key,variants.reversed())).isEqualTo(chosen);if(chosen.get("key").equals("A"))a++;}assertThat(a).isBetween(7800,8200);}
 @Test void weightsAndLifecycleRejectInvalidTransitions(){assertThatThrownBy(()->ExperimentAssignment.assign(UUID.randomUUID(),"x",List.of(Map.of("weight",50)))).hasMessageContaining("10000");assertThat(ExperimentAssignment.transition("RUNNING","PAUSED")).isTrue();assertThat(ExperimentAssignment.transition("PAUSED","RUNNING")).isTrue();assertThat(ExperimentAssignment.transition("COMPLETED","RUNNING")).isFalse();assertThat(ExperimentAssignment.transition("DRAFT","COMPLETED")).isFalse();}
}
