package com.mediafactory;
import com.mediafactory.quality.*;
import com.mediafactory.quality.QualityModels.*;
import com.mediafactory.service.*;
import com.mediafactory.provider.*;
import com.mediafactory.provider.resilience.*;
import com.mediafactory.provider.routing.*;
import com.mediafactory.storage.*;
import org.junit.jupiter.api.*;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.*;
import org.testcontainers.utility.DockerImageName;
import io.micrometer.core.instrument.MeterRegistry;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;
import static org.assertj.core.api.Assertions.*;
@Tag("integration") @Testcontainers
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"media.worker.enabled=false","media.qa.requests-per-minute=1000"})
class QualityIntegrationTest {
 @Container static PostgreSQLContainer<?> postgres=new PostgreSQLContainer<>(DockerImageName.parse("pgvector/pgvector:pg17").asCompatibleSubstituteFor("postgres"));
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",postgres::getJdbcUrl);r.add("spring.datasource.username",postgres::getUsername);r.add("spring.datasource.password",postgres::getPassword);r.add("media.storage.root",()->"build/qa-media/"+UUID.randomUUID());}
 @Autowired JdbcClient db;@Autowired TransactionTemplate tx;@Autowired FactoryService factory;@Autowired QualityReviewService reviews;@Autowired ReviewWorkflowService workflow;@Autowired QaConfiguration config;@Autowired TechnicalQa technical;@Autowired QualityPolicyEngine engine;@Autowired MediaStorage storage;@Autowired ProviderRateLimiter limiter;@Autowired RetryDecisionService retry;@Autowired MeterRegistry metrics;@Autowired ImageGenerationProperties images;@Autowired GenerationAttemptRepository attempts;@Autowired ProviderObservability telemetry;
 @BeforeEach void clean(){db.sql("truncate projects,provider_runtime,provider_request_events cascade").update();}
 GenerationWorker imageWorker(){return new GenerationWorker(db,tx,factory,new ImageProviderRouter(List.of(new MockProviders()),images),images,limiter,retry,attempts,telemetry,storage,technical);}
 QualityWorker worker(VisionQualityProvider... providers){return new QualityWorker(db,tx,reviews,config,technical,engine,storage,limiter,retry,List.of(providers),metrics);}
 UUID asset(String scenario){var p=factory.project("QA","");var c=factory.collection((UUID)p.get("id"),"Review collection");var concept=factory.concept((UUID)c.get("id"),"A landscape","A landscape");factory.generate((UUID)concept.get("id"),"A landscape",128,128,UUID.randomUUID().toString(),null);try(var image=imageWorker()){image.execute(image.claim());}var a=factory.list("assets").getFirst();db.sql("update qa_jobs set scenario=? where review_id=?").params(scenario,a.get("current_review_id")).update();return (UUID)a.get("id");}
 Map<String,Object> current(UUID asset){return reviews.review((UUID)factory.one("assets",asset).get("current_review_id"));}
 void run(){try(var worker=worker(new MockVisionQualityProvider())){worker.execute(worker.claim());}}
 QualityReviewService.HumanCommand command(Map<String,Object> review,String code){return new QualityReviewService.HumanCommand(((Number)review.get("revision")).intValue(),code,"Human evidence");}
 @Test void successPersistsEvidenceSnapshotCostsAndPublicationGate(){UUID a=asset("PERFECT");assertThatThrownBy(()->workflow.publish(a,"test",null)).hasMessageContaining("approval");run();var r=current(a);assertThat(r).containsEntry("execution_status","COMPLETED").containsEntry("final_decision","APPROVED");assertThat(db.sql("select count(*) from quality_dimension_results where review_id=?").param(r.get("id")).query(Integer.class).single()).isEqualTo(9);assertThat(db.sql("select count(*) from generation_costs where asset_id=? and operation='VISUAL_QA'").param(a).query(Integer.class).single()).isEqualTo(1);assertThat(r.get("context_snapshot").toString()).contains("canonical_positive_prompt","A landscape");workflow.publish(a,"test",null);assertThat(factory.one("generations",(UUID)r.get("generation_id"))).containsEntry("status","PUBLISHED");}
 @Test void rejectionCanBeOverriddenWithImmutableAuditAndStaleWriteProtection(){UUID a=asset("WATERMARK");run();var r=current(a);assertThat(r).containsEntry("automatic_decision","REJECTED");UUID id=(UUID)r.get("id");assertThatThrownBy(()->reviews.decide(id,Decision.APPROVED,command(r,null),"operator")).hasMessageContaining("reason");reviews.decide(id,Decision.APPROVED,command(r,"AI_FALSE_POSITIVE"),"operator");assertThat(current(a)).containsEntry("automatic_decision","REJECTED").containsEntry("final_decision","APPROVED").containsEntry("human_override",true);assertThatThrownBy(()->reviews.decide(id,Decision.REJECTED,command(r,"OTHER"),"operator")).hasMessageContaining("changed");assertThatThrownBy(()->db.sql("delete from human_review_actions where review_id=?").param(id).update()).hasMessageContaining("immutable");}
 @Test void automaticApprovalCanBeRejectedWithReasonAndPublicationSqlCannotBypass(){UUID a=asset("PERFECT");run();var r=current(a);reviews.decide((UUID)r.get("id"),Decision.REJECTED,command(r,"AI_FALSE_NEGATIVE"),"operator");assertThat(current(a)).containsEntry("automatic_decision","APPROVED").containsEntry("final_decision","REJECTED");assertThatThrownBy(()->db.sql("insert into publications(id,asset_id,channel) values(?,?,'bypass')").params(UUID.randomUUID(),a).update()).hasMessageContaining("approval");assertThatThrownBy(()->db.sql("update generations set status='PUBLISHED' where id=?").param(r.get("generation_id")).update()).hasMessageContaining("approval");}
 @Test void uncertainHumanApprovalAndRegenerationPreserveLineage(){UUID a=asset("UNCERTAIN");run();var r=current(a);assertThat(r).containsEntry("final_decision","NEEDS_REVIEW");reviews.decide((UUID)r.get("id"),Decision.APPROVED,command(r,null),"operator");r=current(a);String key=UUID.randomUUID().toString();var input=new ReviewWorkflowService.Regenerate(((Number)r.get("revision")).intValue(),"SAME_PROMPT",null,null,null,"Keep the exact prompt");var child=workflow.regenerate((UUID)r.get("id"),key,input);assertThat(child.get("parent_id")).isEqualTo(r.get("generation_id"));assertThat(workflow.regenerate((UUID)r.get("id"),key,input).get("id")).isEqualTo(child.get("id"));assertThat(factory.list("assets")).hasSize(1);assertThat(db.sql("select canonical_positive_prompt from rendered_prompt_snapshots where generation_id=?").param(child.get("id")).query(String.class).single()).isEqualTo("A landscape");}
 @Test void rerunCreatesHistoryWhileOrdinaryEnqueueIsIdempotent(){UUID a=asset("PERFECT");run();var r=current(a);assertThat(reviews.enqueue(a,false,null,null).get("id")).isEqualTo(r.get("id"));var rerun=workflow.rerun((UUID)r.get("id"),((Number)r.get("revision")).intValue(),"UNCERTAIN");assertThat(rerun.get("id")).isNotEqualTo(r.get("id"));run();assertThat(current(a)).containsEntry("final_decision","NEEDS_REVIEW");assertThat(reviews.review((UUID)r.get("id"))).containsEntry("final_decision","APPROVED");}
 @Test void rateLimitRetryUsesPersistedAttemptsThenSucceeds(){UUID a=asset("RATE_LIMIT");run();assertThat(current(a)).containsEntry("execution_status","PENDING");db.sql("update qa_jobs set scenario='PERFECT',available_at=now()").update();run();assertThat(current(a)).containsEntry("execution_status","COMPLETED");assertThat(db.sql("select count(*) from vision_qa_attempts").query(Integer.class).single()).isEqualTo(2);}
 @Test void allProvidersFailAndInvalidOutputNeverRejectContent(){UUID a=asset("INVALID_RESPONSE");run();assertThat(current(a)).containsEntry("execution_status","FAILED").containsEntry("final_decision","NEEDS_REVIEW").containsEntry("automatic_decision",null);assertThatThrownBy(()->workflow.publish(a,"test",null)).hasMessageContaining("approval");}
 @Test void timeoutFallsBackAfterRetryBudget(){UUID a=asset("TIMEOUT");db.sql("update qa_jobs set route='[{\"provider\":\"mock\",\"model\":\"mock-vision-v1\"},{\"provider\":\"backup\",\"model\":\"backup-v1\"}]',provider_attempts=1").update();run();db.sql("update qa_jobs set available_at=now()").update();var backup=new VisionQualityProvider(){public String providerId(){return "backup";}public Set<String> capabilities(){return Set.of("STRUCTURED_EVIDENCE");}public Result analyze(Request r){return new MockVisionQualityProvider().analyze(new Request(r.assetId(),r.generationId(),r.bytes(),r.mediaType(),r.model(),"PERFECT",r.context()));}};try(var w=worker(backup)){w.execute(w.claim());}assertThat(current(a)).containsEntry("final_decision","APPROVED").containsEntry("vision_provider","backup");}
 @Test void duplicateDispatchAndExpiredLeaseCannotApprove(){UUID a=asset("PERFECT");try(var w=worker(new MockVisionQualityProvider())){var job=w.claim();w.execute(job);w.execute(job);}assertThat(db.sql("select count(*) from vision_qa_attempts").query(Integer.class).single()).isEqualTo(1);var r=current(a);workflow.rerun((UUID)r.get("id"),((Number)r.get("revision")).intValue(),null);try(var w=worker(new MockVisionQualityProvider())){var job=w.claim();db.sql("update qa_jobs set locked_at=now()-interval '10 minutes' where id=?").param(job.get("id")).update();w.recover();w.execute(job);}assertThat(current(a)).containsEntry("execution_status","FAILED").containsEntry("final_decision","NEEDS_REVIEW");}
 @Test void humanFindingReopensApprovalWithoutChangingAiEvidence(){UUID a=asset("PERFECT");run();var r=current(a);reviews.addFinding((UUID)r.get("id"),((Number)r.get("revision")).intValue(),new Finding(Category.ARTIFACT,Code.BROKEN_GEOMETRY,Severity.MAJOR,1,true,Source.HUMAN,"Broken roof edge",Map.of()),"operator");assertThat(current(a)).containsEntry("automatic_decision","APPROVED").containsEntry("final_decision","NEEDS_REVIEW");}
 @Test void providerOutageExhaustsBudgetWithoutRejectingContent(){UUID a=asset("PROVIDER_ERROR");run();db.sql("update qa_jobs set available_at=now()").update();run();assertThat(current(a)).containsEntry("execution_status","FAILED").containsEntry("automatic_decision",null).containsEntry("final_decision","NEEDS_REVIEW");assertThat(db.sql("select attempts from qa_jobs").query(Integer.class).single()).isEqualTo(2);}
 @Test void manualRegenerationCreatesNewAdHocSnapshot(){UUID a=asset("UNCERTAIN");run();var r=current(a);var child=workflow.regenerate((UUID)r.get("id"),UUID.randomUUID().toString(),new ReviewWorkflowService.Regenerate(((Number)r.get("revision")).intValue(),"MANUAL_OVERRIDE",null,"A quiet forest","no lettering","Change location"));assertThat(child).containsEntry("parent_id",r.get("generation_id")).containsEntry("prompt","A quiet forest");assertThat(db.sql("select canonical_negative_prompt from rendered_prompt_snapshots where generation_id=?").param(child.get("id")).query(String.class).single()).isEqualTo("no lettering");assertThat(factory.one("generations",(UUID)r.get("generation_id")).get("prompt")).isEqualTo("A landscape");}
 @Test void completedEvidenceAndSupersededReviewsCannotBeEdited(){UUID a=asset("PERFECT");run();var original=current(a);UUID id=(UUID)original.get("id");assertThatThrownBy(()->db.sql("update quality_reviews set automatic_decision='REJECTED' where id=?").param(id).update()).hasMessageContaining("immutable");assertThatThrownBy(()->db.sql("delete from quality_findings where review_id=?").param(id).update()).hasMessageContaining("immutable");var humanPolicy=new QaPolicy("human-test","1",true,64,64,26214400,.01,true,false,.9,.75,config.policy("default").minimumScores(),config.policy("default").rejectCodes());var result=engine.evaluate(humanPolicy,new MockVisionQualityProvider().analyze(new VisionQualityProvider.Request(a,(UUID)original.get("generation_id"),new byte[0],"image/png","mock","PERFECT",Map.of())).evidence().findings(),new MockVisionQualityProvider().analyze(new VisionQualityProvider.Request(a,(UUID)original.get("generation_id"),new byte[0],"image/png","mock","PERFECT",Map.of())).evidence().dimensions(),true,true);assertThat(result).extracting(Evaluation::automaticDecision,Evaluation::finalDecision).containsExactly(Decision.APPROVED,Decision.NEEDS_REVIEW);workflow.rerun(id,((Number)original.get("revision")).intValue(),null);assertThatThrownBy(()->db.sql("update quality_reviews set final_decision='REJECTED' where id=?").param(id).update()).hasMessageContaining("Historical");}
 @Test void oneHundredQueuedAssetsRemainBoundedAndResponsive()throws Exception{
  UUID first=asset("PERFECT");var template=factory.one("assets",first);var generation=factory.one("generations",(UUID)template.get("generation_id"));
  // Unique metadata/keys, shared immutable fixture bytes: this measures scheduling, not image generation throughput.
  for(int i=1;i<100;i++){UUID g=UUID.randomUUID(),a=UUID.randomUUID();db.sql("insert into generations(id,concept_id,status,prompt,width,height) values(?,?,'QA_PENDING','Load fixture',128,128)").params(g,generation.get("concept_id")).update();String key="load/"+a+".png";storage.putOriginal(key,storage.read(template.get("storage_key").toString()),"image/png");db.sql("insert into assets(id,generation_id,storage_key,sha256,media_type,size_bytes,width,height) values(?,?,?,?,'image/png',?,128,128)").params(a,g,key,String.format("%064d",i),template.get("size_bytes")).update();reviews.enqueue(a,false,null,"PERFECT");}
  assertThat(db.sql("select count(*) from qa_jobs").query(Integer.class).single()).isEqualTo(100);
  var active=new AtomicInteger();var maximum=new AtomicInteger();var calls=new AtomicInteger();
  var provider=new VisionQualityProvider(){public String providerId(){return "mock";}public Set<String> capabilities(){return Set.of("image/png");}public Result analyze(Request r){assertThat(org.springframework.transaction.support.TransactionSynchronizationManager.isActualTransactionActive()).isFalse();int n=active.incrementAndGet();maximum.accumulateAndGet(n,Math::max);try{calls.incrementAndGet();Thread.sleep(10);return new MockVisionQualityProvider().analyze(r);}catch(InterruptedException e){throw new RuntimeException(e);}finally{active.decrementAndGet();}}};
  try(var w=worker(provider)){long deadline=System.nanoTime()+TimeUnit.SECONDS.toNanos(40);while(db.sql("select count(*) from qa_jobs where status in ('QUEUED','RUNNING')").query(Integer.class).single()>0&&System.nanoTime()<deadline){w.tick();assertThat(reviews.queue(Map.of(),0,24)).containsKey("items");Thread.sleep(30);}}
  assertThat(calls.get()).isEqualTo(100);assertThat(maximum.get()).isBetween(1,config.concurrency());assertThat(db.sql("select count(*) from qa_jobs where status='SUCCEEDED'").query(Integer.class).single()).isEqualTo(100);
 }
}
