package com.mediafactory;
import com.mediafactory.quality.*;
import com.mediafactory.quality.QualityModels.*;
import com.mediafactory.provider.MockProviders;
import com.mediafactory.provider.ProviderTypes;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import org.springframework.mock.env.MockEnvironment;
import java.util.*;
import static org.assertj.core.api.Assertions.*;

class QualityPolicyTest {
 final QaConfiguration config=new QaConfiguration(new MockEnvironment());final QualityPolicyEngine engine=new QualityPolicyEngine();final MockVisionQualityProvider mock=new MockVisionQualityProvider();
 VisionQualityProvider.Request request(String scenario){return new VisionQualityProvider.Request(UUID.randomUUID(),UUID.randomUUID(),new byte[]{1},"image/png","mock-vision-v1",scenario,Map.of());}
 @Test void perfectApprovesAndHumanPolicyKeepsAutomaticDecision(){var e=mock.analyze(request("PERFECT")).evidence();assertThat(engine.evaluate(config.policy("default"),e.findings(),e.dimensions(),true,true).finalDecision()).isEqualTo(Decision.APPROVED);var p=engine.evaluate(config.policy("stock"),e.findings(),e.dimensions(),true,true);assertThat(p.automaticDecision()).isEqualTo(Decision.APPROVED);assertThat(p.finalDecision()).isEqualTo(Decision.NEEDS_REVIEW);}
 @Test void confidenceIsIndependentFromSeverity(){var e=mock.analyze(request("MAJOR_ARTIFACT")).evidence();assertThat(e.findings().getFirst().confidence()).isEqualTo(.55);assertThat(engine.evaluate(config.policy("default"),e.findings(),e.dimensions(),true,true).finalDecision()).isEqualTo(Decision.NEEDS_REVIEW);}
 @Test void highConfidenceCriticalRejectsAndLowConfidenceCriticalNeedsReview(){var e=mock.analyze(request("WATERMARK")).evidence();assertThat(engine.evaluate(config.policy("default"),e.findings(),e.dimensions(),true,true).finalDecision()).isEqualTo(Decision.REJECTED);var f=new Finding(Category.WATERMARK,Code.POSSIBLE_WATERMARK,Severity.CRITICAL,.5,true,Source.VISION_MODEL,"Uncertain mark",Map.of());assertThat(engine.evaluate(config.policy("default"),List.of(f),e.dimensions(),true,true).finalDecision()).isEqualTo(Decision.NEEDS_REVIEW);}
 @Test void missingAndUncertainDimensionsCannotApprove(){var e=mock.analyze(request("UNCERTAIN")).evidence();assertThat(engine.evaluate(config.policy("default"),e.findings(),e.dimensions(),true,true).finalDecision()).isEqualTo(Decision.NEEDS_REVIEW);assertThat(engine.evaluate(config.policy("default"),List.of(),List.of(),true,true).finalDecision()).isEqualTo(Decision.NEEDS_REVIEW);}
 @Test void infrastructureFailureIsNotContentRejection(){assertThat(engine.evaluate(config.policy("default"),List.of(),List.of(),true,false).finalDecision()).isEqualTo(Decision.NEEDS_REVIEW);}
 @Test void falseFindingsDoNotReject(){var e=mock.analyze(request("PERFECT")).evidence();var finding=new Finding(Category.TECHNICAL,Code.CORRUPT_FILE,Severity.CRITICAL,1,false,Source.TECHNICAL,"File decoded",Map.of());assertThat(engine.evaluate(config.policy("default"),List.of(finding),e.dimensions(),true,true).finalDecision()).isEqualTo(Decision.APPROVED);}
 @Test void anatomyNotApplicableForAbstractMockAndInvalidScoresRejected(){assertThat(mock.analyze(request("PERFECT")).evidence().dimensions().stream().filter(d->d.dimension()==DimensionName.ANATOMY).findFirst().orElseThrow().applicable()).isFalse();assertThatThrownBy(()->new Dimension(DimensionName.ANATOMY,Double.NaN,1,true,"Evidence")).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->new Dimension(DimensionName.ANATOMY,1,1.1,true,"Evidence")).isInstanceOf(IllegalArgumentException.class);}
 @ParameterizedTest @EnumSource(MockVisionQualityProvider.Scenario.class) void allMockScenariosAreDeterministic(MockVisionQualityProvider.Scenario scenario){var r=request(scenario.name());if(Set.of("RATE_LIMIT","TIMEOUT","INVALID_RESPONSE","PROVIDER_ERROR").contains(scenario.name()))assertThatThrownBy(()->mock.analyze(r)).isInstanceOf(com.mediafactory.provider.resilience.ImageGenerationException.class);else{var a=mock.analyze(r);a.evidence().validateVision();assertThat(mock.analyze(r)).isEqualTo(a);assertThat(a.estimatedCost()).isZero();}}
 @Test void technicalChecksProduceEvidenceAndDetectMimeMismatch(){var image=new MockProviders().generate(new ProviderTypes.Request("qa-test","A landscape",128,128)).output().bytes();var qa=new TechnicalQa();var good=qa.inspectStructured(image,"image/png",128,128,false,config.policy("default"));assertThat(good.findings()).anyMatch(f->f.code()==Code.CORRUPT_FILE&&!f.detected());var wrong=qa.inspectStructured(image,"image/jpeg",256,128,true,config.policy("default"));assertThat(wrong.findings()).anyMatch(f->f.code()==Code.CORRUPT_FILE&&f.detected()).anyMatch(f->f.code()==Code.DUPLICATE_SHA256&&f.detected());}
 @Test void technicalResolutionRatioAndTransparencyChecks()throws Exception{var image=new java.awt.image.BufferedImage(128,64,java.awt.image.BufferedImage.TYPE_INT_ARGB);var bytes=new java.io.ByteArrayOutputStream();javax.imageio.ImageIO.write(image,"png",bytes);var e=new TechnicalQa().inspectStructured(bytes.toByteArray(),"image/png",256,256,false,config.policy("wallpaper-standard"));assertThat(e.findings()).anyMatch(f->f.code()==Code.RESOLUTION_TOO_LOW&&f.detected()).anyMatch(f->f.code()==Code.WRONG_ASPECT_RATIO&&f.detected()).anyMatch(f->f.code()==Code.UNEXPECTED_TRANSPARENCY&&f.detected()).anyMatch(f->f.code()==Code.NEAR_SOLID_IMAGE&&f.detected()&&f.confidence()<.9);}
 @Test void corruptAndOversizeAreBounded(){var qa=new TechnicalQa();assertThat(qa.inspectStructured(new byte[0],"image/png",128,128,false,config.policy("default")).findings()).anyMatch(f->f.code()==Code.CORRUPT_FILE&&f.detected());assertThat(qa.inspectStructured(new byte[26*1024*1024],"image/png",128,128,false,config.policy("default")).findings()).anyMatch(f->f.code()==Code.FILE_SIZE&&f.detected());}
 @Test void invalidVisionJsonFailsInsteadOfApproving(){assertThatThrownBy(()->OpenAiVisionQualityProvider.parseEvidence("{\"findings\":[],\"dimensions\":[]}")).hasMessageContaining("schema validation");assertThatThrownBy(()->OpenAiVisionQualityProvider.parseEvidence("not-json")).hasMessageContaining("schema validation");}
 @Test void strictVisionSchemaIncludesAllDimensionsAndNoDecision(){var schema=OpenAiVisionQualityProvider.schema();assertThat(schema.toString()).contains("PROMPT_COMPLIANCE","MALFORMED_FACE","additionalProperties=false").doesNotContain("automaticDecision");}
 @Test void realVisionCannotUseMockFallback(){var c=new QaConfiguration(new MockEnvironment().withProperty("media.qa.provider","openai").withProperty("media.qa.fallback-providers","mock"));assertThatThrownBy(c::route).hasMessageContaining("cannot fall back");}
}
