import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {ArrowUpRight,CheckCircle2,Cpu,Layers3,Play,RotateCw,X,ZoomIn,ZoomOut} from 'lucide-react';
import {api,type Row} from './api';
import './processing.css';

type Profile={id:string;key:string;version:number;status:string;definition:Record<string,unknown>};
type Rect={x:number;y:number;width:number;height:number};
type Crop={rectangle:Rect;focalRegions:(Rect&{type:string})[];warnings:string[];safeZones?:{top:number;bottom:number}};
type Run={id:string;source_asset_id:string;status:string;attempt:number;failure_code:string|null;completed_variants:number;plan:{nodes:{key:string;operation:string}[]};steps?:Record<string,unknown>[];manifests?:unknown[]};
type Variant={id:string;kind:string;width:number;height:number;format:string;size_bytes:number;megapixels:number;validation_status:string;profile_version:number};
type Worker={status:string;device?:string;gpuAvailable:boolean;vramBytes?:number;activeJobs:number;models?:{id:string;available:boolean;scale:number}[]};
const path='/v1';

export function ProcessingWorkspace({initialAsset}:{initialAsset?:string}){
 const client=useQueryClient();const [tab,setTab]=useState('Queue');const [selected,setSelected]=useState(initialAsset??'');
 const [profiles,setProfiles]=useState<string[]>(['PREVIEW']);const [batch,setBatch]=useState<string[]>([]);const [notice,setNotice]=useState('');const [detail,setDetail]=useState('');
 const [cropProfile,setCropProfile]=useState('');const [manual,setManual]=useState<Record<string,Rect>>({});const [compare,setCompare]=useState<Variant|null>(null);
 const assets=useQuery({queryKey:['/assets'],queryFn:()=>api<Row[]>('/assets')});
 const catalog=useQuery({queryKey:['processing-profiles'],queryFn:()=>api<Profile[]>(path+'/processing-profiles')});
 const runs=useQuery({queryKey:['processing-runs'],queryFn:()=>api<Run[]>(path+'/processing-runs'),refetchInterval:3000});
 const worker=useQuery({queryKey:['processing-worker'],queryFn:()=>api<Worker>(path+'/processing-worker'),refetchInterval:10000});
 const variants=useQuery({queryKey:['processing-variants',selected],queryFn:()=>api<Variant[]>(`${path}/assets/${selected}/variants`),enabled:!!selected,refetchInterval:4000});
 const run=useQuery({queryKey:['processing-run',detail],queryFn:()=>api<Run>(`${path}/processing-runs/${detail}`),enabled:!!detail,refetchInterval:3000});
 const crop=useQuery({queryKey:['crop-preview',selected,cropProfile],queryFn:()=>api<Crop>(`${path}/assets/${selected}/crop-preview/${cropProfile}`),enabled:!!selected&&!!cropProfile,retry:false});
 const action=useMutation({mutationFn:({url,body}:{url:string;body?:unknown})=>api<unknown>(url,body??{}),onSuccess:(data)=>{client.invalidateQueries({queryKey:['processing-runs']});const rejected=Array.isArray(data)?data.filter(r=>r.error):[];setNotice(rejected.length?`${rejected.length} assets could not be queued: ${rejected.slice(0,3).map(r=>r.error).join('; ')}`:'Request saved. Processing continues in the background.');},onError:e=>setNotice(e.message)});
 const current=assets.data?.find(a=>String(a.id)===selected);const published=(catalog.data??[]).filter((p,i,all)=>p.status==='PUBLISHED'&&!all.slice(0,i).some(x=>x.key===p.key&&x.status==='PUBLISHED'));
 const list=(runs.data??[]).filter(r=>tab==='Queue'?['PENDING','RUNNING'].includes(r.status):tab==='Active'?r.status==='RUNNING':tab==='Completed'?r.status==='COMPLETED':['FAILED','PARTIALLY_COMPLETED','CANCELLED'].includes(r.status));
 const submit=()=>action.mutate({url:`${path}/assets/${selected}/process`,body:{profiles,manualCrops:manual}});
 return <div className="processing-workspace">
  <div className="processing-banner"><div><span className="eyebrow">POST-PRODUCTION STUDIO</span><h2>One master. Every destination.</h2><p>Shape approved originals into immutable, validated deliverables.</p></div><div className="worker-pill"><Cpu size={22}/><div>{worker.data?.status??'Connecting'}<small>{worker.data?.device?.toUpperCase()??'—'} · {worker.data?.activeJobs??0} active</small></div></div></div>
  {(notice||runs.error||catalog.error)&&<div role="status" className="notice">{notice||runs.error?.message||catalog.error?.message}</div>}
  <div className="processing-stats">{[['Queued',(runs.data??[]).filter(r=>r.status==='PENDING').length],['Active',(runs.data??[]).filter(r=>r.status==='RUNNING').length],['Completed',(runs.data??[]).filter(r=>r.status==='COMPLETED').length],['Needs attention',(runs.data??[]).filter(r=>['FAILED','PARTIALLY_COMPLETED'].includes(r.status)).length]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>
  <div className="processing-columns"><section className="panel processing-create"><h3><Layers3 size={18}/> Create deliverables</h3><label>Source master<select aria-label="Source master" value={selected} onChange={e=>{setSelected(e.target.value);setManual({});setCropProfile('');}}><option value="">Choose an approved image…</option>{assets.data?.map(a=><option key={String(a.id)} value={String(a.id)}>{String(a.id).slice(0,8)} · {a.width} × {a.height}</option>)}</select></label>
   {current&&<div className="processing-source"><img src={`/api/assets/${selected}/content`} alt="Original master"/><div><b>Immutable original</b><small>{current.width} × {current.height} · {(Number(current.width)*Number(current.height)/1e6).toFixed(2)} MP</small><small>{String(current.media_type)}</small></div></div>}
   <label>Output profiles</label><div className="profile-choices">{published.map(p=><label className={profiles.includes(p.key)?'chosen':''} key={p.id}><input type="checkbox" checked={profiles.includes(p.key)} onChange={()=>setProfiles(old=>old.includes(p.key)?old.filter(k=>k!==p.key):[...old,p.key])}/><span>{p.key.replaceAll('_',' ')}<small>{String(p.definition.width)} × {String(p.definition.height)} · {String(p.definition.format)} · v{p.version}</small></span></label>)}</div>
   <button className="primary" disabled={!selected||!profiles.length||action.isPending} onClick={submit}><Play size={16}/>Start processing</button>
   <p className="muted">Only QA-approved masters are accepted. The server checks approval before queuing and execution.</p>
   {!!selected&&<><label>Composition preview<select aria-label="Crop profile" value={cropProfile} onChange={e=>setCropProfile(e.target.value)}><option value="">Select a crop profile…</option>{published.filter(p=>['SMART_FILL','FILL'].includes(String(p.definition.mode))).map(p=><option key={p.key}>{p.key}</option>)}</select></label>{crop.isFetching&&<p>Detecting focal regions…</p>}{crop.error&&<p role="alert">{crop.error.message}</p>}{crop.data&&<CropEditor source={selected} crop={crop.data} value={manual[cropProfile]} onChange={value=>setManual(old=>{const next={...old};if(value)next[cropProfile]=value;else delete next[cropProfile];return next;})}/>}</>}
  </section><div><div className="processing-tabs">{['Queue','Active','Completed','Failed','GPU Worker','Profiles','Batch'].map(t=><button className={tab===t?'selected':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>
   {['Queue','Active','Completed','Failed'].includes(tab)&&<section className="panel processing-runs">{list.length===0?<div className="processing-empty"><CheckCircle2 size={30}/><h3>Nothing here yet</h3><p>Choose a master and output profiles to begin.</p></div>:list.map(r=><article key={r.id}><img src={`/api/assets/${r.source_asset_id}/content`} alt="Processing source"/><div><button className="text-button" onClick={()=>setDetail(r.id)}>{r.source_asset_id.slice(0,8)} <ArrowUpRight size={14}/></button><small>{r.plan.nodes.filter(n=>n.operation==='DERIVE').map(n=>n.key.replaceAll('_',' ')).join(' · ')}</small><progress max={r.plan.nodes.length-1} value={r.completed_variants}/><small>{r.completed_variants}/{r.plan.nodes.length-1} variants · attempt {r.attempt}</small>{r.failure_code&&<span className="processing-error">{r.failure_code.replaceAll('_',' ')}</span>}</div><div><span className="badge">{r.status.replaceAll('_',' ')}</span>{['PENDING','RUNNING'].includes(r.status)?<button onClick={()=>action.mutate({url:`${path}/processing-runs/${r.id}/cancel`})}>Cancel</button>:r.status!=='COMPLETED'&&<button onClick={()=>action.mutate({url:`${path}/processing-runs/${r.id}/retry`})}><RotateCw size={14}/>Retry failed</button>}</div></article>)}</section>}
   {tab==='GPU Worker'&&<section className="panel processing-detail"><h3>Local processing worker</h3><p>{worker.data?.gpuAvailable?'CUDA device detected':'CPU execution'} · {worker.data?.vramBytes?`${(worker.data.vramBytes/2**30).toFixed(1)} GB VRAM`:'VRAM unavailable'}</p><p>One execution slot. Tiled inference and bounded memory recovery.</p>{worker.data?.models?.map(m=><p key={m.id}>{m.id} · {m.scale}× <span className="badge">{m.available?'Provisioned':'Model missing'}</span></p>)}</section>}
   {tab==='Profiles'&&<section className="panel processing-detail"><h3>Versioned output profiles</h3><p>Published definitions are immutable. Create a draft through the profiles API to change a preset.</p>{catalog.data?.map(p=><details key={p.id}><summary>{p.key} · v{p.version} · {p.status}</summary><pre>{JSON.stringify(p.definition,null,2)}</pre></details>)}</section>}
   {tab==='Batch'&&<section className="panel processing-detail"><h3>Batch processing</h3><p>Select up to 100 masters. Each asset keeps its own progress and retry state.</p><div className="batch-assets">{assets.data?.map(a=><label key={String(a.id)}><input type="checkbox" checked={batch.includes(String(a.id))} onChange={()=>setBatch(old=>old.includes(String(a.id))?old.filter(id=>id!==a.id):[...old,String(a.id)].slice(0,100))}/><img src={`/api/assets/${a.id}/content`} alt="Batch source"/><span>{String(a.id).slice(0,8)}</span></label>)}</div><button className="primary" disabled={!batch.length||!profiles.length||action.isPending} onClick={()=>action.mutate({url:path+'/processing-batches',body:{assetIds:batch,profiles}})}>Process {batch.length} masters</button></section>}
   {selected&&<section className="panel processing-variants"><h3>Deliverables <span>{variants.data?.length??0}</span></h3><div className="variant-grid">{variants.data?.map(v=><button key={v.id} onClick={()=>setCompare(v)}><img src={`${path==='/v1'?'/api/v1':''}/variants/${v.id}/content`} alt={v.kind}/><b>{v.kind.replaceAll('_',' ')}</b><small>{v.width} × {v.height} · {v.format} · {Number(v.megapixels??0).toFixed(2)} MP</small><small>{v.validation_status??'Legacy derivative'} · v{v.profile_version??'—'}</small></button>)}</div>{!variants.data?.length&&<p className="muted">Validated outputs will appear here.</p>}</section>}
  </div></div>
  {detail&&<div className="modal-backdrop"><section className="modal processing-manifest"><button className="close" aria-label="Close run details" onClick={()=>setDetail('')}><X/></button><h2>Processing record</h2><p>{run.data?.status} · {detail}</p><h3>Steps</h3>{run.data?.steps?.map((s,i)=><p key={i}>{String(s.node_key)} · {String(s.status)} {String(s.skip_reason??s.error_code??'')}</p>)}<details><summary>Immutable execution manifests</summary><pre>{JSON.stringify(run.data?.manifests,null,2)}</pre></details></section></div>}
  {compare&&<Compare source={selected} variant={compare} close={()=>setCompare(null)}/>}
 </div>;
}

export function CropEditor({source,crop,value,onChange}:{source:string;crop:Crop;value?:Rect;onChange:(r?:Rect)=>void}){
 const r=value??crop.rectangle;
 return <div className="crop-editor"><div className="crop-stage" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;const box=e.currentTarget.getBoundingClientRect();onChange({...r,x:Math.max(0,Math.min(1-r.width,(e.clientX-box.left)/box.width-r.width/2)),y:Math.max(0,Math.min(1-r.height,(e.clientY-box.top)/box.height-r.height/2))});}}><img src={`/api/assets/${source}/content`} alt="Crop composition preview" draggable={false}/><div className="crop-safe-top" style={{left:`${r.x*100}%`,top:`${r.y*100}%`,width:`${r.width*100}%`,height:`${r.height*(crop.safeZones?.top??0)*100}%`}}/><div className="crop-safe-bottom" style={{left:`${r.x*100}%`,top:`${(r.y+r.height*(1-(crop.safeZones?.bottom??0)))*100}%`,width:`${r.width*100}%`,height:`${r.height*(crop.safeZones?.bottom??0)*100}%`}}/>{crop.focalRegions.map((f,i)=><div key={i} className="focal-region" style={{left:`${f.x*100}%`,top:`${f.y*100}%`,width:`${f.width*100}%`,height:`${f.height*100}%`}}><span>{f.type}</span></div>)}<div className="crop-window" style={{left:`${r.x*100}%`,top:`${r.y*100}%`,width:`${r.width*100}%`,height:`${r.height*100}%`}}/></div><small>{value?'MANUAL · audited human override':'AUTO · subject-aware composition'}</small><label>Crop scale<input aria-label="Crop scale" type="range" min="0.25" max="1" step="0.01" value={r.width/crop.rectangle.width} onChange={e=>{const scale=Number(e.target.value),w=crop.rectangle.width*scale,h=crop.rectangle.height*scale;onChange({x:Math.max(0,Math.min(1-w,r.x+(r.width-w)/2)),y:Math.max(0,Math.min(1-h,r.y+(r.height-h)/2)),width:w,height:h});}}/></label><button onClick={()=>onChange(undefined)}>Reset to automatic</button>{crop.warnings.map(w=><p className="processing-error" key={w}>{w.replaceAll('_',' ')}</p>)}</div>;
}
function Compare({source,variant,close}:{source:string;variant:Variant;close:()=>void}){
 const [zoom,setZoom]=useState(0);
 return <div className="modal-backdrop"><section className="processing-compare"><header><h2>Original / {variant.kind.replaceAll('_',' ')}</h2><div><button onClick={()=>setZoom(0)}>Fit</button><button onClick={()=>setZoom(1)}>100%</button><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(.25,(z||1)-.25))}><ZoomOut/></button><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(4,(z||1)+.25))}><ZoomIn/></button><button aria-label="Close comparison" onClick={close}><X/></button></div></header><div className="compare-panes">{[`/api/assets/${source}/content`,`/api/v1/variants/${variant.id}/content`].map((url,i)=><div key={url} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId)){e.currentTarget.scrollLeft-=e.movementX;e.currentTarget.scrollTop-=e.movementY;}}}><ZoomImage url={url} label={i?'Processed variant':'Original'} zoom={zoom}/></div>)}</div><p>{variant.width} × {variant.height} · {variant.format} · {variant.validation_status} · drag to pan</p></section></div>;
}
function ZoomImage({url,label,zoom}:{url:string;label:string;zoom:number}){
 const [width,setWidth]=useState(0);
 return <img src={url} alt={label} draggable={false} onLoad={e=>setWidth(e.currentTarget.naturalWidth)} style={zoom?{maxWidth:'none',maxHeight:'none',width:width*zoom,height:'auto'}:{}}/>;
}
