import { afterEach, expect, it, vi } from 'vitest';
import { cleanup, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { PromptStudio, VariableInputs, VersionDiff, type Version } from './PromptStudio';
import { GenerationDialog, GenerationDetails } from './ProviderPanels';
import { useState } from 'react';
afterEach(()=>{cleanup();vi.restoreAllMocks();});
const version:Version={id:'version-1',prompt_template_id:'template-1',version:1,status:'PUBLISHED',positive_template:'A {{subject}}',negative_template:'blurry',change_description:'Initial',revision:1,variables:[{name:'subject',label:'Subject',type:'STRING',required:true},{name:'count',label:'Count',type:'INTEGER',required:false,defaultValue:2}],created_at:'2026-09-24T00:00:00Z',template_name:'Animals'};
const template={id:'template-1',key:'animals',name:'Animals',category:'WALLPAPER',status:'ACTIVE',revision:0,current_version:1,running_experiments:0,updated_at:'2026-09-24T00:00:00Z'};
function wrap(element:React.ReactNode){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}})}>{element}</QueryClientProvider>);}
function fixtures(url:unknown){const path=String(url);if(path.endsWith('/prompt-templates'))return [template];if(path.includes('/prompt-templates/template-1/versions'))return [version];if(path.endsWith('/prompt-versions/version-1'))return version;if(path.endsWith('/prompt-versions'))return [version];if(path.includes('/render-draft'))return {canonical:{positivePrompt:'A wolf',negativePrompt:'blurry'},warnings:[]};return [];}
it('shows library versions and keeps published editor read-only',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(async url=>new Response(JSON.stringify(fixtures(url))));wrap(<PromptStudio section="Prompt Library"/>);expect(await screen.findByText('Animals')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:/Open history/}));await userEvent.click(await screen.findByRole('button',{name:'View'}));const positive=await screen.findByLabelText('Positive template');expect(positive).toHaveAttribute('readonly');expect(screen.getByRole('button',{name:/Create draft copy/})).toBeEnabled();expect(screen.queryByRole('button',{name:'Publish version'})).not.toBeInTheDocument();});
it('live preview calls only the renderer and displays variable errors',async()=>{const calls=vi.spyOn(globalThis,'fetch').mockImplementation(async url=>String(url).includes('/render-draft')?new Response(JSON.stringify({detail:'Required value is missing',variable:'subject'}),{status:400}):new Response(JSON.stringify(fixtures(url))));wrap(<PromptStudio section="Prompt Editor"/>);await screen.findByRole('option',{name:'Animals'});await userEvent.selectOptions(screen.getByLabelText('Template'),'template-1');await waitFor(()=>expect(screen.getByRole('option',{name:'v1 · PUBLISHED'})).toBeInTheDocument());await userEvent.selectOptions(screen.getByLabelText('Version'),'version-1');expect(await screen.findByText('Required value is missing')).toBeInTheDocument();expect(calls.mock.calls.some(c=>String(c[0]).includes('/generations'))).toBe(false);});
it('variable input sends numbers rather than numeric strings',async()=>{const change=vi.fn();function Harness(){const [values,setValues]=useState<Record<string,unknown>>({});return <VariableInputs definitions={[version.variables[1]]} values={values} onChange={v=>{setValues(v);change(v);}}/>;}render(<Harness/>);await userEvent.clear(screen.getByLabelText('Count'));await userEvent.type(screen.getByLabelText('Count'),'3');expect(change).toHaveBeenLastCalledWith({count:3});});
it('compares positive negative and variable definitions visibly',()=>{render(<VersionDiff before={version} after={{...version,version:2,positive_template:'New {{subject}}',variables:[]}}/>);expect(screen.getByText('Positive template · changed')).toBeInTheDocument();expect(screen.getByText('Negative template · unchanged')).toBeInTheDocument();expect(screen.getByText('Variable definitions · changed')).toBeInTheDocument();});
it('queues a template generation with typed variables and no raw prompt',async()=>{const calls=vi.spyOn(globalThis,'fetch').mockImplementation(async url=>new Response(JSON.stringify(String(url).includes('/generations/images')?{generationId:'g'}:fixtures(url))));const created=vi.fn();wrap(<GenerationDialog concepts={[{id:'concept',name:'Concept'}]} providers={[]} close={()=>{}} onCreated={created}/>);await screen.findByRole('option',{name:'Animals · v1'});await userEvent.selectOptions(screen.getByLabelText('Prompt source'),'version-1');await userEvent.type(await screen.findByLabelText('Subject *'),'wolf');await userEvent.click(screen.getByRole('button',{name:'Generate image'}));await waitFor(()=>expect(created).toHaveBeenCalledWith('g'));const body=JSON.parse(String(calls.mock.calls.find(c=>String(c[0]).includes('/generations/images'))![1]?.body));expect(body).toMatchObject({promptVersionId:'version-1',variables:{subject:'wolf'}});expect(body).not.toHaveProperty('prompt');});
it('displays historical snapshots directly without fetching current templates',async()=>{const calls=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(JSON.stringify({status:'QA_PENDING',selected_provider:'mock',final_provider:'mock',provider_route:[],attempts:[],assets:[],job:{id:'j',status:'SUCCEEDED'},costs:[],promptSnapshots:[{id:'s',kind:'TEMPLATE',provider:'mock',template_version:1,canonical_positive_prompt:'Old wolf',canonical_negative_prompt:'blurry',adapted_positive_prompt:'Old wolf\nNegative constraints: blurry',adapted_negative_prompt:'',adaptation_strategy:'MERGED_V1',variables:{subject:'wolf'},presets:[],composition:{},warnings:[],experiment_id:null}]})));wrap(<GenerationDetails id="g" close={()=>{}}/>);await userEvent.click(await screen.findByText('Stored prompt · mock · TEMPLATE v1'));expect(screen.getByText('Old wolf')).toBeInTheDocument();expect(calls.mock.calls.every(c=>String(c[0]).includes('/generations/g'))).toBe(true);});
