import {afterEach,describe,expect,it,vi} from 'vitest';
import {cleanup,render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {SimilarityWorkspace} from './SimilarityWorkspace';
afterEach(()=>{cleanup();vi.restoreAllMocks()});
const pair={id:'pair',source_asset_id:'source',target_asset_id:'target',sha256_match:false,phash_distance:6,embedding_similarity:.97,automatic_classification:'NEAR_DUPLICATE',final_classification:'NEAR_DUPLICATE',human_classification:null,revision:3,explanation:'Both independent measures agree.',context:{sameCollection:true,sameConcept:false,samePromptVersion:true,sameGenerationFamily:false}};
function setup(page:string){const fetch=vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const path=String(input);let result:unknown=[];if(path.includes('similarity-comparisons?'))result=[pair];else if(path.includes('embedding-models'))result=[{id:'model',model:'CLIP',version:'revision123',active:true}];else if(path.includes('embedding-jobs?'))result=[{id:'job',type:'GENERATE_ASSET_EMBEDDING',status:'FAILED',attempts:4,progress:0,failure_reason:'Worker unavailable'}];else if(path.includes('/collections'))result=[{id:'collection',name:'Forest',similarity_profile:'WALLPAPER'}];if(init?.method==='POST')result={ok:true};return new Response(JSON.stringify(result),{status:200,headers:{'Content-Type':'application/json'}})});render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><SimilarityWorkspace page={page}/></QueryClientProvider>);return fetch;}
describe('Similarity workspace',()=>{
 it('displays separate metrics and sends a revision-protected human override',async()=>{const fetch=setup('Duplicate Review');await userEvent.click(await screen.findByRole('button',{name:/SHA different/}));expect(screen.getByRole('dialog',{name:'Compare originals'})).toBeInTheDocument();expect(screen.getByText('pHash distance: 6')).toBeInTheDocument();expect(screen.getByText('Cosine similarity: 0.9700')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Mark distinct'})).toBeDisabled();await userEvent.type(screen.getByLabelText('Review reason'),'Different subject pose');await userEvent.click(screen.getByRole('button',{name:'Mark distinct'}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith('/api/v1/similarity-comparisons/pair/mark-distinct',expect.objectContaining({body:JSON.stringify({revision:3,classification:'DISTINCT',reason:'Different subject pose'})})));});
 it('shows worker failure and retries the durable job',async()=>{const fetch=setup('Embedding Jobs');expect(await screen.findByText('Worker unavailable')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Retry'}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith('/api/v1/embedding-jobs/job/retry',expect.objectContaining({method:'POST'})));});
 it('semantic search explicitly describes meaning and has no duplicate claim',()=>{setup('Similarity Explorer');expect(screen.getByRole('heading',{name:'Search by meaning'})).toBeInTheDocument();expect(screen.getByLabelText('Semantic query')).toBeInTheDocument();});
});
