import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {api} from './api';
import './similarity.css';

type Asset={id:string;width:number;height:number};
type Comparison={id:string;source_asset_id:string;target_asset_id:string;sha256_match:boolean;phash_distance:number|null;embedding_similarity:number|null;automatic_classification:string;human_classification:string|null;final_classification:string;revision:number;explanation:string;context:Record<string,boolean>};
type Model={id:string;model:string;version:string;provider:string;active:boolean;dimension:number};
type Collection={id:string;name:string;similarity_profile:string};
type Group={id:string;type:string;revision:number;canonical_asset_id:string|null;member_count:number};
type Job={id:string;type:string;status:string;attempts:number;progress:number;failure_reason:string|null};
type Cluster={id:string;outlier:boolean;representative_asset_id:string|null;members:{asset_id:string;distance_to_centroid:number|null}[]};
type Diversity={run:null|{id:string;statistics:Record<string,number|null>};clusters:Cluster[];embeddingCoverage:{total:number;ready:number}};
const classifications=['EXACT_DUPLICATE','PERCEPTUAL_DUPLICATE','NEAR_DUPLICATE','VISUALLY_SIMILAR','SEMANTICALLY_SIMILAR','DISTINCT'];
const label=(text:string)=>text.replaceAll('_',' ').toLowerCase();
function Photo({id,alt='Asset preview'}:{id:string;alt?:string}){return <img loading="lazy" src={`/api/assets/${id}/content`} alt={alt}/>}
function useData<T>(path:string,enabled=true){return useQuery({queryKey:[path],queryFn:()=>api<T>(path),enabled,refetchInterval:10000})}
export function SimilarityDashboard(){const query=useData<Record<string,number>>('/v1/similarity/dashboard');return <section aria-label="Similarity overview" className="similarity-stats">{Object.entries(query.data??{}).map(([key,value])=><div key={key}><small>{label(key)}</small><strong>{value}</strong></div>)}</section>}

export function SimilarityWorkspace({page}:{page:string}){
 const client=useQueryClient();const [error,setError]=useState('');const [notice,setNotice]=useState('');const [collection,setCollection]=useState('');const [classification,setClassification]=useState('');const [generationModel,setGenerationModel]=useState('');const [after,setAfter]=useState('');const [pageIndex,setPageIndex]=useState(0);
 const [source,setSource]=useState('');const [scope,setScope]=useState('GLOBAL');const [minimum,setMinimum]=useState(.7);const [query,setQuery]=useState('');const [semantic,setSemantic]=useState<{asset:Asset;cosineSimilarity:number}[]>([]);const [pair,setPair]=useState<Comparison|null>(null);const [reason,setReason]=useState('');const [group,setGroup]=useState<Group|null>(null);const [model,setModel]=useState('');const [changedPrompt,setChangedPrompt]=useState('');
 const collections=useData<Collection[]>('/collections');const assets=useData<Asset[]>('/assets');const models=useData<Model[]>('/v1/embedding-models');const activeModel=models.data?.find(m=>m.active);const targetModel=model||activeModel?.id||'';
 const filters=new URLSearchParams({page:String(pageIndex),...(classification?{classification}:{}),...(collection?{collection}:{}),...(generationModel?{generationModel}:{}),...(after?{after:after+'T00:00:00Z'}:{})});
 const comparisons=useData<Comparison[]>(`/v1/similarity-comparisons?${filters}`,page==='Duplicate Review');
 const similar=useData<{state:string;source:Asset;candidates:{asset:Asset;embeddingSimilarity:number|null;comparison:Comparison|null}[]}>(`/v1/assets/${source}/similar?scope=${scope}&minimumSimilarity=${minimum}${classification?'&classification='+classification:''}`,page==='Similarity Explorer'&&!!source);
 const groups=useData<Group[]>('/v1/duplicate-groups',page==='Duplicate Review');const members=useData<{group:Group;members:{asset_id:string;width:number;height:number}[]}>(`/v1/duplicate-groups/${group?.id}`,!!group);
 const diversity=useData<Diversity>(`/v1/collections/${collection}/diversity`,page==='Collection Diversity'&&!!collection);
 const jobs=useData<Job[]>(`/v1/embedding-jobs?page=${pageIndex}`,page==='Embedding Jobs');
 const batches=useData<{id:string;status:string;dispatched:number;total:number;revision:number;pause_reason:string}[]>('/v1/generation-batches',page==='Collection Diversity');
 const action=useMutation({mutationFn:({path,body,key,method}:{path:string;body?:unknown;key?:string;method?:string})=>api(path,body??{},key,method),onSuccess:()=>{client.invalidateQueries();setNotice('Saved. The latest evidence is available.');setError('');setPair(null);setGroup(null)},onError:e=>setError(e.message)});
 const search=useMutation({mutationFn:()=>api<{asset:Asset;cosineSimilarity:number}[]>('/v1/assets/search/semantic',{query,limit:30}),onSuccess:setSemantic,onError:e=>setError(e.message)});
 const collectionSelect=<label>Collection<select aria-label="Collection" value={collection} onChange={e=>{setCollection(e.target.value);setPageIndex(0)}}><option value="">Choose collection</option>{collections.data?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>;
 const classSelect=<label>Classification<select value={classification} onChange={e=>{setClassification(e.target.value);setPageIndex(0)}}><option value="">All classifications</option>{classifications.map(c=><option key={c}>{c}</option>)}</select></label>;
 const enqueue=(type:string)=>action.mutate({path:'/v1/embedding-jobs',body:{type,modelId:targetModel,collectionId:collection||null},key:crypto.randomUUID()});
 const failure=error||comparisons.error?.message||similar.error?.message||diversity.error?.message||jobs.error?.message;
 const pager=(count:number)=><div className="similarity-controls"><button disabled={pageIndex===0} onClick={()=>setPageIndex(v=>v-1)}>Previous</button><span>Page {pageIndex+1}</span><button disabled={count<50} onClick={()=>setPageIndex(v=>v+1)}>Next</button></div>;
 return <div className="similarity-workspace">
  {failure&&<div role="alert" className="error">{failure}</div>}{notice&&<p role="status">{notice}</p>}
  {page==='Duplicate Review'&&<>
   <div className="similarity-intro"><h2>Make every original count.</h2><p>Compare the evidence, record your judgment, and choose the original to publish.</p></div>
   <div className="similarity-controls">{collectionSelect}{classSelect}<label>Generation model<input value={generationModel} onChange={e=>setGenerationModel(e.target.value)} placeholder="Any model"/></label><label>Created since<input type="date" value={after} onChange={e=>setAfter(e.target.value)}/></label></div>
   <div className="comparison-grid">{comparisons.data?.map(c=><button className="comparison-card" key={c.id} onClick={()=>{setPair(c);setReason('')}}><div className="paired-images"><Photo id={c.source_asset_id} alt="Source original"/><Photo id={c.target_asset_id} alt="Candidate original"/></div><span className="badge">{label(c.final_classification)}</span><div className="comparison-metrics"><span>SHA {c.sha256_match?'match':'different'}</span><span>pHash {c.phash_distance??'pending'}</span><span>Cosine {c.embedding_similarity?.toFixed(3)??'pending'}</span></div><small>{c.human_classification?'Human reviewed':'Awaiting human judgment'}</small></button>)}</div>
   {comparisons.data?.length===0&&<p className="empty">No comparisons match these filters. Embedding jobs create evidence as originals arrive.</p>}{pager(comparisons.data?.length??0)}
   <h2>Duplicate families</h2><div className="family-grid">{groups.data?.map(g=><button key={g.id} onClick={()=>{setGroup(g);setReason('')}}><strong>{label(g.type)}</strong><span>{g.member_count} originals</span><small>{g.canonical_asset_id?'Canonical selected':'Choose a canonical original'}</small></button>)}</div>
  </>}
  {page==='Similarity Explorer'&&<>
   <div className="similarity-controls"><label>Source original<select value={source} onChange={e=>setSource(e.target.value)}><option value="">Choose original</option>{assets.data?.map(a=><option key={a.id} value={a.id}>{a.id.slice(0,8)} · {a.width} × {a.height}</option>)}</select></label><label>Search scope<select value={scope} onChange={e=>setScope(e.target.value)}><option>GLOBAL</option><option>PROJECT</option><option>SAME_COLLECTION</option></select></label>{classSelect}<label>Minimum cosine {minimum.toFixed(2)}<input type="range" min="0" max="1" step="0.01" value={minimum} onChange={e=>setMinimum(Number(e.target.value))}/></label></div>
   {source&&<div className="source-preview"><Photo id={source}/><div><h2>Source original</h2><p>Analysis: {similar.data?.state??'Loading'}</p><p>A high cosine value indicates related content. It does not establish a duplicate.</p></div></div>}
   <div className="similarity-assets">{similar.data?.candidates.map(c=><button key={c.asset.id} disabled={!c.comparison} onClick={()=>{setPair(c.comparison);setReason('')}}><Photo id={c.asset.id}/><strong>{c.embeddingSimilarity?.toFixed(3)??'No embedding'}</strong><small>{c.comparison?label(c.comparison.final_classification):'Related candidate'}</small></button>)}</div>
   <form className="semantic-search" onSubmit={e=>{e.preventDefault();search.mutate()}}><h2>Search by meaning</h2><p>Describe a subject, setting, or visual idea.</p><input aria-label="Semantic query" value={query} onChange={e=>setQuery(e.target.value)} placeholder="A wolf in a moonlit forest" required maxLength={16000}/><button className="primary" disabled={search.isPending}>{search.isPending?'Searching…':'Find related originals'}</button></form>
   <div className="similarity-assets">{semantic.map(c=><button key={c.asset.id} onClick={()=>setSource(c.asset.id)}><Photo id={c.asset.id}/><strong>{c.cosineSimilarity.toFixed(3)}</strong><small>Semantic similarity</small></button>)}</div>
  </>}
  {page==='Collection Diversity'&&<>
   <div className="similarity-controls">{collectionSelect}<button disabled={!collection||action.isPending} onClick={()=>enqueue('CLUSTER_COLLECTION')}>Analyze collection</button><label>Similarity policy<select disabled={!collection} value={collections.data?.find(c=>c.id===collection)?.similarity_profile??'WALLPAPER'} onChange={e=>action.mutate({path:`/v1/collections/${collection}/similarity-profile`,body:{profile:e.target.value},method:'PUT'})}>{['WALLPAPER','STOCK_STRICT','SOCIAL','GENERATION_DIVERSITY'].map(p=><option key={p}>{p}</option>)}</select></label></div>
   {diversity.data&&<><p>Embedding coverage: {diversity.data.embeddingCoverage.ready} / {diversity.data.embeddingCoverage.total} originals</p>{diversity.data.run?<><div className="similarity-stats">{Object.entries(diversity.data.run.statistics).map(([k,v])=><div key={k}><small>{k.replace(/([A-Z])/g,' $1')}</small><strong>{typeof v==='number'?Number.isInteger(v)?v:v.toFixed(3):'—'}</strong></div>)}</div><p>Visual families are analytical groupings. Outliers are originals outside a dense family.</p>{diversity.data.clusters.map(c=><section className="cluster" key={c.id}><h3>{c.outlier?'Outliers':'Visual family'} · {c.members.length} originals</h3>{c.representative_asset_id&&<div className="cluster-representative"><Photo id={c.representative_asset_id} alt="Cluster representative"/><span>Representative original</span></div>}<div className="cluster-members">{c.members.map(m=><figure key={m.asset_id}><Photo id={m.asset_id}/><figcaption>{m.distance_to_centroid==null?'Noise':`Distance ${m.distance_to_centroid.toFixed(3)}`}</figcaption></figure>)}</div></section>)}</>:<p className="empty">No analysis yet. Backfill embeddings, then analyze this collection.</p>}</>}
   <h2>Protected generation batches</h2>{batches.data?.map(b=><div className="batch-row" key={b.id}><strong>{b.dispatched} / {b.total}</strong><span>{label(b.status)}</span><p>{b.pause_reason}</p>{b.status==='PAUSED_DIVERSITY'&&<><input aria-label="Batch decision reason" placeholder="Decision reason" value={reason} onChange={e=>setReason(e.target.value)}/>{['CONTINUE','STOP'].map(a=><button key={a} disabled={!reason.trim()||action.isPending} onClick={()=>action.mutate({path:`/v1/generation-batches/${b.id}/actions`,body:{revision:b.revision,action:a,reason}})}>{label(a)}</button>)}<input aria-label="Changed batch prompt" placeholder="New prompt for remaining generations" value={changedPrompt} onChange={e=>setChangedPrompt(e.target.value)}/><button disabled={!reason.trim()||!changedPrompt.trim()||action.isPending} onClick={()=>action.mutate({path:`/v1/generation-batches/${b.id}/actions`,body:{revision:b.revision,action:'CHANGE_PROMPT',reason,prompt:{prompt:changedPrompt}}})}>Change prompt and continue</button></>}</div>)}
  </>}
  {page==='Embedding Jobs'&&<>
   <div className="similarity-intro"><h2>Versioned, local inference.</h2><p>Backfill originals, inspect failures, and activate a model after complete coverage. Historical embeddings remain available.</p></div>
   <div className="similarity-controls">{collectionSelect}<label>Embedding model<select value={targetModel} onChange={e=>setModel(e.target.value)}>{models.data?.map(m=><option key={m.id} value={m.id}>{m.model} · {m.version.slice(0,8)} {m.active?'· active':''}</option>)}</select></label><button onClick={()=>enqueue('BACKFILL')} disabled={!targetModel||action.isPending}>Backfill originals</button><button onClick={()=>enqueue('REINDEX')} disabled={!targetModel||action.isPending}>Reindex model</button><button onClick={()=>action.mutate({path:'/v1/embedding-models',body:{provider:'local-clip'}})}>Discover worker model</button><button disabled={!targetModel||targetModel===activeModel?.id||action.isPending} onClick={()=>action.mutate({path:`/v1/embedding-models/${targetModel}/activate`})}>Activate selected model</button></div>
   <p>Local inference records duration and device. External API cost is zero; compute cost is unpriced.</p><div className="similarity-table"><table><thead><tr><th>Operation</th><th>Status</th><th>Attempts</th><th>Progress</th><th>Details</th><th>Action</th></tr></thead><tbody>{jobs.data?.map(j=><tr key={j.id}><td>{label(j.type)}</td><td>{j.status}</td><td>{j.attempts}</td><td>{j.progress} queued</td><td>{j.failure_reason??'—'}</td><td>{j.status==='FAILED'&&<button disabled={action.isPending} onClick={()=>action.mutate({path:`/v1/embedding-jobs/${j.id}/retry`})}>Retry</button>}</td></tr>)}</tbody></table></div>{pager(jobs.data?.length??0)}
  </>}
  {pair&&<div className="similarity-overlay"><section role="dialog" aria-modal="true" aria-label="Compare originals" className="similarity-dialog"><button className="dialog-close" onClick={()=>setPair(null)}>Close</button><h2>Compare originals</h2><div className="paired-images"><Photo id={pair.source_asset_id} alt="Source original"/><Photo id={pair.target_asset_id} alt="Candidate original"/></div><div className="comparison-metrics"><span>SHA-256: {pair.sha256_match?'identical bytes':'different bytes'}</span><span>pHash distance: {pair.phash_distance??'unavailable'}</span><span>Cosine similarity: {pair.embedding_similarity?.toFixed(4)??'unavailable'}</span></div><p>Automatic: {label(pair.automatic_classification)} · Final: {label(pair.final_classification)}</p><p>{pair.explanation}</p><div className="comparison-metrics">{Object.entries(pair.context).filter(([k])=>k.startsWith('same')).map(([k,v])=><span key={k}>{k.replace(/([A-Z])/g,' $1')}: {v?'yes':'no'}</span>)}</div><label>Review reason<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={2000}/></label><div className="similarity-controls">{[['DISTINCT','Mark distinct'],['NEAR_DUPLICATE','Confirm near duplicate'],['PERCEPTUAL_DUPLICATE','Confirm duplicate']].map(([value,text])=><button key={value} disabled={!reason.trim()||action.isPending} onClick={()=>action.mutate({path:`/v1/similarity-comparisons/${pair.id}/${value==='DISTINCT'?'mark-distinct':'confirm'}`,body:{revision:pair.revision,classification:value,reason}})}>{text}</button>)}</div>{error&&<p role="alert">{error}</p>}</section></div>}
  {group&&<div className="similarity-overlay"><section role="dialog" aria-modal="true" aria-label="Choose canonical original" className="similarity-dialog"><button onClick={()=>setGroup(null)}>Close</button><h2>Choose canonical original</h2><p>Choose the preferred master. Every original and its history remain stored.</p><label>Selection reason<input value={reason} onChange={e=>setReason(e.target.value)} maxLength={2000}/></label><div className="similarity-assets">{members.data?.members.map(m=><button key={m.asset_id} disabled={!reason.trim()||action.isPending} onClick={()=>action.mutate({path:`/v1/duplicate-groups/${group.id}/canonical`,body:{assetId:m.asset_id,revision:members.data!.group.revision,reason}})}><Photo id={m.asset_id}/><span>{m.width} × {m.height}</span><strong>{m.asset_id===members.data?.group.canonical_asset_id?'Current canonical':'Select canonical'}</strong></button>)}</div>{error&&<p role="alert">{error}</p>}</section></div>}
 </div>
}
