import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {VideoWorkspace} from './VideoWorkspace';
afterEach(()=>{cleanup();vi.restoreAllMocks();});
function setup(){const p={id:'v1',status:'REVIEW',revision:3,concept_name:'Quiet landscape',thumbnail_id:'thumb',raw_asset_id:'raw',current_run_id:'run',master_variant_id:'master'};const fetcher=vi.spyOn(globalThis,'fetch').mockImplementation(async(input,opts)=>{const path=String(input);let result:unknown=[];if(path.endsWith('/video/productions'))result=[p];if(path.endsWith('/video/productions/v1'))result={...p,variants:[{id:'master',kind:'MASTER_VIDEO',video_processing_run_id:'run',width:720,height:1280,size_bytes:1000},{id:'loop',kind:'LOOP_PREVIEW',video_processing_run_id:'run',width:360,height:640,size_bytes:500}],qa:[{evidence:{semanticLimitation:'Human temporal review is mandatory'}}],runs:[{id:'run',version:1}]};if(path.endsWith('/video/providers'))result=[{provider:'mock-video',enabled:true,model:'deterministic-motion-v1'},{provider:'runway',enabled:false}];if(path.endsWith('/video/profiles'))result=[{id:'profile',profile_key:'WALLPAPER_LOOP',version:1}];if(path.endsWith('/assets'))result=[{id:'image',generation_id:'g'}];if(path.endsWith('/generations'))result=[{id:'g',status:'APPROVED'}];if(path.endsWith('/video/dashboard'))result={review:1};if(opts?.method==='POST')result={id:'new'};return new Response(JSON.stringify(result));});render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><VideoWorkspace/></QueryClientProvider>);return fetcher;}
it('uses thumbnail cards without automatically streaming masters',async()=>{setup();expect(await screen.findByAltText('Quiet landscape')).toHaveAttribute('src','/api/v1/video/variants/thumb/content');expect(document.querySelector('video')).toBeNull();});
it('queues a free mock production with an idempotency key',async()=>{const f=setup();await screen.findByRole('option',{name:'image'});await userEvent.selectOptions(await screen.findByLabelText('Approved source image'),'image');await userEvent.click(screen.getByRole('button',{name:'Queue video'}));await waitFor(()=>expect(f.mock.calls.some(([path,o])=>String(path).endsWith('/video/productions')&&o?.method==='POST'&&JSON.parse(o.body as string).provider==='mock-video'&&!!(o.headers as Record<string,string>)['Idempotency-Key'])).toBe(true));});
it('requires viewing acknowledgement before approval',async()=>{const f=setup();await userEvent.click(await screen.findByRole('button',{name:'Review motion'}));const approve=await screen.findByRole('button',{name:'Approve video'});expect(approve).toBeDisabled();await userEvent.click(screen.getByLabelText('I watched the video and reviewed temporal defects and loop continuity.'));await userEvent.click(approve);await waitFor(()=>expect(f.mock.calls.some(([path,o])=>String(path).endsWith('/v1/approve')&&JSON.parse(o?.body as string).revision===3)).toBe(true));});
it('reprocesses the existing raw video using an explicit loop strategy',async()=>{const f=setup();await userEvent.click(await screen.findByRole('button',{name:'Review motion'}));await userEvent.selectOptions(await screen.findByLabelText('Local loop strategy'),'CROSSFADE');await userEvent.click(screen.getByRole('button',{name:'Reprocess · no new AI generation'}));await waitFor(()=>expect(f.mock.calls.some(([path,o])=>String(path).endsWith('/v1/reprocess')&&JSON.parse(o?.body as string).settings.loopStrategy==='CROSSFADE')).toBe(true));});
