import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {ArrowUpRight,Check,Download,Layers3,Moon,Pause,Play,Plus,RefreshCw,Send,X} from 'lucide-react';
import {api} from './api';
import './wallpaper.css';

type Metadata={title:string;slug:string;description?:string;tags?:string[];premium?:boolean;featured?:boolean;category?:string};
type Amoled={blackPixelRatio:number;nearBlackPixelRatio:number;meanLuminance:number;brightPixelRatio:number;classification:string;warnings:string[]};
type Variant={id:string;kind:string;width:number;height:number;format:string;validation_status:string};
type Production={id:string;collection_id:string;concept_id:string;status:string;revision:number;profile_key:string;profile_snapshot?:{processingProfiles:string[]};qa?:{final_decision:string};similarity?:{id:string;final_classification:string;explanation:unknown}[];metadata:Metadata;thumbnail_id?:string;master_asset_id?:string;processing_run_id?:string;amoled_result?:Amoled;failure_code?:string;variants?:Variant[];packages?:{id:string;version:number;approved_at?:string;manifest:unknown}[];publications?:{id:string;status:string;target:string;failure_code?:string}[];events?:{to_status:string;created_at:string}[]};
type Collection={id:string;name:string;slug:string;amoled:boolean;production_status?:string;target_approved?:number};
type Profile={key:string;definition:{amoled:boolean}};
type Progress={ready:number;generated:number;rejected:number;published:number;attempts:number;active:number;plan:{revision:number;target_approved?:number;status:string;failure_reason?:string};costs:{currency:string;total:number}[]};
const tabs=['Overview','Collections','Production Queue','Wallpaper Review','AMOLED Review','Publication Queue','Published','Failures'] as const;
const ready=['PUBLICATION_REVIEW','APPROVED_FOR_PUBLICATION','PUBLISHED','UNPUBLISHED'];

export function WallpaperWorkspace({onProcess}:{onProcess:(asset:string,profiles?:string[])=>void}){
 const client=useQueryClient();
 const [tab,setTab]=useState<string>('Overview'),[notice,setNotice]=useState(''),[selected,setSelected]=useState<string[]>([]),[detail,setDetail]=useState(''),[collection,setCollection]=useState('');
 const [profile,setProfile]=useState('ANDROID_STANDARD'),[concept,setConcept]=useState(''),[title,setTitle]=useState(''),[subject,setSubject]=useState('');
 const [collectionTitle,setCollectionTitle]=useState(''),[theme,setTheme]=useState(''),[amoled,setAmoled]=useState(false),[project,setProject]=useState(''),[target,setTarget]=useState(10),[maxAttempts,setMaxAttempts]=useState(20);
 const [dry,setDry]=useState<unknown>(),[editing,setEditing]=useState<Metadata>();
 const [reprocessingRun,setReprocessingRun]=useState('');
 const q=<T,>(path:string)=>useQuery({queryKey:[path],queryFn:()=>api<T>(path),refetchInterval:5000});
 const productions=q<Production[]>('/v1/wallpaper-productions'),collections=q<Collection[]>('/v1/wallpaper-collections'),profiles=q<Profile[]>('/v1/wallpaper-profiles');
 const projects=q<{id:string;name:string}[]>('/projects'),concepts=q<{id:string;name:string;collection_id:string}[]>('/concepts');
 const exports=q<{id:string;status:string;failure_code?:string}[]>('/v1/wallpaper-exports');
 const processingRuns=q<{id:string;source_asset_id:string;status:string}[]>('/v1/processing-runs');
 const dashboard=q<Record<string,number>>('/v1/wallpaper-dashboard');
 const details=useQuery({queryKey:['wallpaper',detail],queryFn:()=>api<Production>(`/v1/wallpaper-productions/${detail}`),enabled:!!detail,refetchInterval:3000});
 const progress=useQuery({queryKey:['wallpaper-collection',collection],queryFn:()=>api<Progress>(`/v1/wallpaper-collections/${collection}/production-status`),enabled:!!collection,refetchInterval:5000});
 const action=useMutation({mutationFn:async(fn:()=>Promise<unknown>)=>fn(),onSuccess:()=>{client.invalidateQueries();setNotice('Saved');},onError:e=>setNotice(e.message)});
 const run=(fn:()=>Promise<unknown>)=>action.mutate(fn);
 const post=(path:string,body:unknown={})=>api(path,body,crypto.randomUUID());
 const slug=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`wallpaper-${Date.now()}`;
 const list=productions.data??[],current=details.data;
 const visible=list.filter(w=>(!collection||w.collection_id===collection)&&(tab==='AMOLED Review'?w.profile_key==='ANDROID_AMOLED':tab==='Wallpaper Review'?w.status==='PUBLICATION_REVIEW':tab==='Publication Queue'?['APPROVED_FOR_PUBLICATION','PUBLISHING','PUBLICATION_FAILED'].includes(w.status):tab==='Published'?w.status==='PUBLISHED':tab==='Failures'?/FAILED|REJECTED|PAUSED/.test(w.status):true));
 const bulk=(operation:string)=>run(async()=>{
   const results=await Promise.allSettled(selected.map(async id=>{
     const w=list.find(p=>p.id===id)!;
     if(operation==='publish')return post(`/v1/wallpapers/${id}/publish`,{target:'MOCK'});
     if(operation==='prepare')return post(`/v1/wallpapers/${id}/prepare-publication`);
     if(operation==='approve'){const full=await api<Production>(`/v1/wallpaper-productions/${id}`);if(!full.packages?.[0])throw Error('Prepare and inspect the publication package first');return post(`/v1/wallpapers/${id}/approve-publication`,{packageId:full.packages[0].id,revision:full.revision});}
     return post(`/v1/wallpaper-productions/${id}/reject`,{revision:w.revision,reason:'Rejected during wallpaper review'});
   }));
   const failed=results.filter(r=>r.status==='rejected');if(failed.length)throw Error(`${results.length-failed.length} saved; ${failed.length} failed. ${failed.map(r=>(r as PromiseRejectedResult).reason.message).join('; ')}`);
 });
 return <div className="wallpaper-workspace">
  <section className="wallpaper-hero"><div><span className="eyebrow">WALLPAPER FACTORY</span><h2>Made for the everyday canvas.</h2><p>One concept. A considered collection. Every screen.</p></div><div className="wallpaper-orbit"><Moon size={42}/><span>ANDROID · AMOLED</span></div></section>
  <div className="wallpaper-kpis">{[['Generated today',dashboard.data?.generated_today??0],['QA approved',dashboard.data?.qa_approved??0],['Similarity rejected',dashboard.data?.similarity_rejected??0],['Ready for review',dashboard.data?.waiting_publication_review??0],['Published today',dashboard.data?.published_today??0],['AMOLED ready',dashboard.data?.amoled_ready??0],['Processing ready',dashboard.data?.processing_ready??0],['Pipeline failures',dashboard.data?.pipeline_failures??0]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>
  {(notice||productions.error||collections.error)&&<p className="notice" role="status">{notice||productions.error?.message||collections.error?.message}</p>}
  <div className="wallpaper-tabs">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?'selected':''}>{t}</button>)}</div>
  <div className="wallpaper-layout"><div className="panel wallpaper-controls">
   <h3><Layers3 size={18}/> Production studio</h3>
   <label>Collection<select aria-label="Wallpaper collection" value={collection} onChange={e=>{setCollection(e.target.value);setConcept('');setProfile(collections.data?.find(c=>c.id===e.target.value)?.amoled?'ANDROID_AMOLED':'ANDROID_STANDARD');}}><option value="">All collections</option>{collections.data?.map(c=><option value={c.id} key={c.id}>{c.name}{c.amoled?' · AMOLED':''}</option>)}</select></label>
   <label>Profile<select aria-label="Wallpaper profile" value={profile} onChange={e=>setProfile(e.target.value)}>{profiles.data?.map(p=><option key={p.key}>{p.key}</option>)}</select></label>
   <label>Concept<select aria-label="Wallpaper concept" value={concept} onChange={e=>setConcept(e.target.value)}><option value="">Choose a concept</option>{concepts.data?.filter(c=>c.collection_id===collection).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>
   <label>Wallpaper title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Neon sentinel"/></label>
   <button className="primary" disabled={!concept||!title||action.isPending} onClick={()=>run(()=>post('/v1/wallpaper-productions',{conceptId:concept,profile,metadata:{title,slug:slug(title),premium:false,featured:false,tags:[]}}))}><Play size={15}/> Start production</button>
   <details><summary>Add a concept</summary><label>Subject & direction<textarea value={subject} onChange={e=>setSubject(e.target.value)} placeholder="A lone silver wolf beneath an aurora…"/></label><button disabled={!collection||!title||!subject||action.isPending} onClick={()=>run(()=>post('/concepts',{collectionId:collection,name:title,prompt:subject}))}><Plus size={14}/>Save concept</button></details>
   {collection&&<details open={tab==='Collections'}><summary>Collection production</summary><label>Target ready<input type="number" min={1} max={1000} value={target} onChange={e=>setTarget(Number(e.target.value))}/></label><label>Maximum attempts<input type="number" min={target} max={2000} value={maxAttempts} onChange={e=>setMaxAttempts(Number(e.target.value))}/></label><p className="muted">Controlled batches of 2. Local mock budget: 0 USD. Publication always needs approval.</p><button disabled={action.isPending} onClick={()=>run(()=>post(`/v1/wallpaper-collections/${collection}/produce`,{targetApproved:target,batchSize:2,maxAttempts,maximumCost:0,reservedCostPerAttempt:0,wallpaperProfile:profile}))}>Produce collection</button>{progress.data?.plan.status&&<><p>{progress.data.plan.status} · {progress.data.plan.failure_reason}</p><button onClick={()=>run(()=>post(`/v1/wallpaper-collections/${collection}/${progress.data?.plan.status==='RUNNING'?'pause':'resume'}`,{revision:progress.data?.plan.revision,reason:'Operator action'}))}>Pause / resume</button></>}</details>}
   <details open={tab==='Collections'&&!collection}><summary>New wallpaper collection</summary><label>Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="">Choose project</option>{projects.data?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Collection title<input value={collectionTitle} onChange={e=>setCollectionTitle(e.target.value)}/></label><label>Theme<input value={theme} onChange={e=>setTheme(e.target.value)}/></label><label className="wallpaper-check"><input type="checkbox" checked={amoled} onChange={e=>setAmoled(e.target.checked)}/>AMOLED collection</label><button disabled={!project||!collectionTitle||action.isPending} onClick={()=>run(()=>post('/v1/wallpaper-collections',{projectId:project,title:collectionTitle,slug:slug(collectionTitle),theme,style:'Cinematic',description:theme,amoled}))}>Create collection</button></details>
  </div><section>
   {collection&&progress.data&&<div className="panel wallpaper-progress"><b>Collection progress</b><span>{progress.data.ready} / {progress.data.plan.target_approved??target} ready · {progress.data.generated} generated · {progress.data.rejected} rejected</span><progress value={progress.data.ready} max={progress.data.plan.target_approved??target}/><small>{progress.data.costs.map(c=>`${c.total} ${c.currency}`).join(' · ')||'No recorded cost'}</small><button onClick={()=>run(()=>post(`/v1/wallpaper-collections/${collection}/export`))}><Download size={14}/>Export collection</button></div>}
   <div className="wallpaper-toolbar"><span>{visible.length} wallpapers · {selected.length} selected</span><button disabled={!selected.length||action.isPending} onClick={()=>bulk('prepare')}>Prepare selected</button><button disabled={!selected.length||action.isPending} onClick={()=>bulk('approve')}>Approve selected packages</button><button disabled={!selected.length||action.isPending} onClick={()=>bulk('publish')}>Publish approved to mock</button><button disabled={!selected.length||action.isPending} onClick={()=>bulk('reject')}>Reject selected</button></div>
   <div className="wallpaper-grid">{visible.map(w=><article key={w.id} className="wallpaper-card"><div className="wallpaper-image">{w.thumbnail_id?<img loading="lazy" src={`/api/v1/variants/${w.thumbnail_id}/content`} alt={w.metadata.title}/>:<div className="wallpaper-placeholder"><Moon/><span>{w.status.replaceAll('_',' ')}</span></div>}<input aria-label={`Select ${w.metadata.title}`} type="checkbox" checked={selected.includes(w.id)} onChange={()=>setSelected(s=>s.includes(w.id)?s.filter(id=>id!==w.id):[...s,w.id])}/>{w.profile_key==='ANDROID_AMOLED'&&<span className="amoled-chip">AMOLED</span>}</div><div className="wallpaper-card-body"><h3>{w.metadata.title}</h3><span className="badge">{w.status.replaceAll('_',' ')}</span>{w.failure_code&&<small>{w.failure_code}</small>}<button onClick={()=>{setDetail(w.id);setDry(undefined);setEditing(undefined);}}>Inspect wallpaper <ArrowUpRight size={14}/></button></div></article>)}</div>
   {!visible.length&&<div className="panel wallpaper-empty"><Layers3 size={36}/><h3>Your next collection starts here.</h3><p>Create a collection, add a concept, then start production.</p></div>}
   {!!exports.data?.length&&<details className="panel wallpaper-exports"><summary>Export packages</summary>{exports.data.map(e=><p key={e.id}>{e.status} {e.failure_code} {e.status==='COMPLETED'&&<a href={`/api/v1/wallpaper-exports/${e.id}/content`}>Download immutable ZIP</a>}</p>)}</details>}
  </section></div>
  {detail&&<div className="modal-backdrop"><section className="modal wallpaper-detail" role="dialog" aria-label="Wallpaper review"><button className="close" aria-label="Close wallpaper review" onClick={()=>setDetail('')}><X/></button>{current?<><span className="eyebrow">PUBLICATION REVIEW</span><h2>{current.metadata.title}</h2>{notice&&<p className="notice" role="status">{notice}</p>}<p>{current.status} · {current.profile_key}</p><div className="wallpaper-variant-grid">{current.variants?.map(v=><figure key={v.id}><a href={`/api/v1/variants/${v.id}/content`} target="_blank" rel="noreferrer"><img src={`/api/v1/variants/${v.kind==='WALLPAPER_MASTER'?(current.variants?.find(x=>x.kind==='ANDROID_PREVIEW')?.id??v.id):v.id}/content`} alt={v.kind} loading="lazy"/></a><figcaption>{v.kind}<small>{v.width} × {v.height} · {v.format} · {v.validation_status}</small></figcaption></figure>)}</div>
   <section className="panel"><h3>Quality & similarity</h3><p>QA decision: {current.qa?.final_decision??'Pending'}</p><p>{current.similarity?.length?current.similarity.map(s=>s.final_classification).join(' · '):'No duplicate comparisons recorded'}</p></section>
   {current.amoled_result&&<section className="panel amoled-stats"><h3>{current.amoled_result.classification}</h3>{[['Black',current.amoled_result.blackPixelRatio],['Near-black',current.amoled_result.nearBlackPixelRatio],['Bright pixels',current.amoled_result.brightPixelRatio],['Mean luminance',current.amoled_result.meanLuminance]].map(([label,value])=><p key={label}>{label}<b>{(Number(value)*100).toFixed(1)}%</b></p>)}<p>{current.amoled_result.warnings.join(' · ')}</p></section>}
   <div className="wallpaper-actions">
    {ready.includes(current.status)&&<button onClick={()=>run(()=>post(`/v1/wallpapers/${current.id}/prepare-publication`))}>Prepare package</button>}
    {current.packages?.[0]&&['PUBLICATION_REVIEW','UNPUBLISHED'].includes(current.status)&&<button className="primary" disabled={action.isPending} onClick={()=>run(()=>post(`/v1/wallpapers/${current.id}/approve-publication`,{packageId:current.packages![0].id,revision:current.revision}))}><Check size={15}/>Approve package v{current.packages[0].version}</button>}
    {current.status==='APPROVED_FOR_PUBLICATION'&&<button disabled={action.isPending} onClick={()=>run(()=>post(`/v1/wallpapers/${current.id}/publish`,{target:'MOCK'}))}><Send size={15}/>Publish to mock catalog</button>}
    <button onClick={()=>run(async()=>{setDry(await post(`/v1/wallpapers/${current.id}/publication-dry-run`,{target:'MOCK'}));})}>Dry run</button>
    {current.status==='PUBLISHED'&&<button onClick={()=>run(()=>post(`/v1/wallpapers/${current.id}/unpublish`,{target:'MOCK'}))}>Unpublish</button>}
    {ready.includes(current.status)&&<button onClick={()=>run(()=>post(`/v1/wallpapers/${current.id}/export`))}><Download size={15}/>Export package</button>}
    {current.master_asset_id&&<button onClick={()=>onProcess(current.master_asset_id!,current.profile_snapshot?.processingProfiles??['WALLPAPER_MASTER','ANDROID_FHD_PORTRAIT','ANDROID_QHD_PORTRAIT','ANDROID_GENERIC_PORTRAIT','ANDROID_PREVIEW','ANDROID_THUMBNAIL'])}>Open crop editor</button>}
    <button onClick={()=>run(()=>post(`/v1/wallpaper-productions/${current.id}/regenerate`))}><RefreshCw size={15}/>Regenerate</button>
    {['PUBLICATION_REVIEW','APPROVED_FOR_PUBLICATION'].includes(current.status)&&<button onClick={()=>run(()=>post(`/v1/wallpaper-productions/${current.id}/reject`,{revision:current.revision,reason:'Rejected during publication review'}))}>Reject</button>}
    {!ready.includes(current.status)&&<button onClick={()=>run(()=>post(`/v1/wallpaper-productions/${current.id}/${current.status==='PAUSED'?'resume':'pause'}`,{revision:current.revision,reason:'Operator review'}))}><Pause size={15}/>Pause / resume</button>}
    <button onClick={()=>setEditing({...current.metadata})}>Edit metadata</button>
    {['PUBLICATION_REVIEW','PROCESSING_FAILED','UNPUBLISHED'].includes(current.status)&&<label>Attach corrected processing run<select value={reprocessingRun} onChange={e=>setReprocessingRun(e.target.value)}><option value="">Select a new run</option>{processingRuns.data?.filter(r=>r.source_asset_id===current.master_asset_id&&r.id!==current.processing_run_id).map(r=><option key={r.id} value={r.id}>{r.id.slice(0,8)} · {r.status}</option>)}</select><button disabled={!reprocessingRun||action.isPending} onClick={()=>run(()=>post(`/v1/wallpaper-productions/${current.id}/reprocess`,{revision:current.revision,processingRunId:reprocessingRun}))}>Use corrected variants</button></label>}
   </div>
   {editing&&<section className="panel wallpaper-metadata"><label>Title<input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Description<textarea value={editing.description??''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label>Tags<input value={editing.tags?.join(', ')??''} onChange={e=>setEditing({...editing,tags:e.target.value.split(',').map(s=>s.trim())})}/></label><label className="wallpaper-check"><input type="checkbox" checked={!!editing.premium} onChange={e=>setEditing({...editing,premium:e.target.checked})}/>Premium</label><button onClick={()=>run(()=>post(`/v1/wallpaper-productions/${current.id}/metadata`,{revision:current.revision,metadata:editing}))}>Save metadata</button></section>}
   {dry!==undefined&&<pre className="wallpaper-json">{JSON.stringify(dry,null,2)}</pre>}
   {current.packages?.[0]&&<details><summary>Publication manifest v{current.packages[0].version}</summary><pre className="wallpaper-json">{JSON.stringify(current.packages[0].manifest,null,2)}</pre></details>}
   {current.publications?.map(p=><p key={p.id}>{p.target} · {p.status} {p.failure_code}{p.status==='FAILED'&&<button onClick={()=>run(()=>post(`/v1/wallpaper-deliveries/${p.id}/retry`))}>Retry delivery</button>}</p>)}
   <details><summary>Production history</summary>{current.events?.map((e,i)=><p key={i}>{e.to_status} · {new Date(e.created_at).toLocaleString()}</p>)}</details>
  </>:<p>{details.error?.message??'Loading wallpaper…'}</p>}</section></div>}
 </div>;
}


