import {chromium} from 'playwright';
import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1516,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:3000');
await page.getByRole('button',{name:'Processing',exact:true}).click();
await page.getByText('One master. Every destination.').waitFor();
await page.getByRole('button',{name:'Completed',exact:true}).click();
await page.waitForTimeout(1200);
const select=page.getByLabel('Source master');
const values=await select.locator('option').evaluateAll(options=>options.map(o=>o.value).filter(Boolean));
if(values.length)await select.selectOption(values[0]);
await page.getByText('Deliverables',{exact:false}).last().waitFor();
await fs.mkdir('test-results',{recursive:true});
await page.screenshot({path:'test-results/processing-dashboard.png',fullPage:true});
if(errors.length)throw Error(errors.join('\n'));
console.log('Processing UI smoke passed');
await browser.close();
